import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createCISDockerPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "CIS-DOCKER-001",
      name: "Run Container as Non-Root User",
      description: "Containers should not run as the root user. A non-root user must be specified via the USER instruction or securityContext.",
      category: "container-security",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Add a non-root user in the Dockerfile (e.g., `RUN adduser -D appuser && USER appuser`). In docker-compose, set `user: appuser` or `user: 1000:1000`. Never run containers as UID 0.",
      checks: [
        { id: "CIS-DOCKER-001-C1", description: "Non-root USER instruction present in Dockerfile", status: "not-implemented" },
        { id: "CIS-DOCKER-001-C2", description: "user field set to non-root in docker-compose", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-002",
      name: "Use Trusted Base Images Only",
      description: "Base images should come from trusted, verified registries — not random Docker Hub images.",
      category: "supply-chain",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use official images from verified publishers. Pin images to specific versions. Scan images with Trivy or Grype before deployment. Use private registry with image signing (cosign).",
      checks: [
        { id: "CIS-DOCKER-002-C1", description: "Base images from trusted/official sources", status: "not-implemented" },
        { id: "CIS-DOCKER-002-C2", description: "Image scanning in CI/CD pipeline", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-003",
      name: "Do Not Use :latest Tag",
      description: "Using the :latest tag makes builds non-reproducible and can introduce unexpected breaking changes.",
      category: "supply-chain",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Pin all FROM images to a specific version tag or digest (e.g., `node:20.11-alpine` instead of `node:latest`). Use SHA256 digests for maximum reproducibility.",
      checks: [
        { id: "CIS-DOCKER-003-C1", description: "No :latest tag in FROM instructions", status: "not-implemented" },
        { id: "CIS-DOCKER-003-C2", description: "No :latest tag in docker-compose image references", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-004",
      name: "Set Memory Limits",
      description: "Containers must have memory limits to prevent resource exhaustion and DoS.",
      category: "resource-management",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "In docker-compose, set `mem_limit:` (e.g., `mem_limit: 512m`). In Kubernetes, set `resources.limits.memory`. In Docker run, use `--memory` flag.",
      checks: [
        { id: "CIS-DOCKER-004-C1", description: "Memory limit defined for all containers", status: "not-implemented" },
        { id: "CIS-DOCKER-004-C2", description: "Memory request defined (Kubernetes)", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-005",
      name: "Set CPU Limits",
      description: "Containers must have CPU limits to ensure fair scheduling and prevent resource monopolization.",
      category: "resource-management",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "In docker-compose, set `cpus:` (e.g., `cpus: '0.5'`). In Kubernetes, set `resources.limits.cpu`. In Docker run, use `--cpus` flag.",
      checks: [
        { id: "CIS-DOCKER-005-C1", description: "CPU limit defined for all containers", status: "not-implemented" },
        { id: "CIS-DOCKER-005-C2", description: "CPU request defined (Kubernetes)", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-006",
      name: "Read-Only Root Filesystem",
      description: "Container root filesystem should be read-only to prevent attackers from writing malicious files.",
      category: "container-security",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "In docker-compose, set `read_only: true`. In Kubernetes, set `securityContext.readOnlyRootFilesystem: true`. Mount writable volumes only for specific paths that need writes (e.g., /tmp).",
      checks: [
        { id: "CIS-DOCKER-006-C1", description: "read_only set to true in docker-compose", status: "not-implemented" },
        { id: "CIS-DOCKER-006-C2", description: "readOnlyRootFilesystem set to true (Kubernetes)", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-007",
      name: "No Privileged Containers",
      description: "Privileged containers have access to all host devices and kernel capabilities. This essentially grants root access to the host.",
      category: "container-security",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Never set `privileged: true` in docker-compose or Kubernetes securityContext. If specific capabilities are needed, add only those via `cap_add` (compose) or `securityContext.capabilities.add` (K8s).",
      checks: [
        { id: "CIS-DOCKER-007-C1", description: "No privileged: true in docker-compose", status: "not-implemented" },
        { id: "CIS-DOCKER-007-C2", description: "No privileged: true in Kubernetes manifests", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-008",
      name: "Drop Dangerous Capabilities",
      description: "Containers should drop all capabilities by default and only add those explicitly needed.",
      category: "container-security",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "In docker-compose, use `cap_drop: [ALL]` then selectively add needed caps. In Kubernetes, set `securityContext.capabilities.drop: [ALL]`. Dangerous capabilities include SYS_ADMIN, NET_ADMIN, DAC_OVERRIDE.",
      checks: [
        { id: "CIS-DOCKER-008-C1", description: "cap_drop: ALL in docker-compose or K8s", status: "not-implemented" },
        { id: "CIS-DOCKER-008-C2", description: "Only explicitly needed capabilities added", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-009",
      name: "Use HEALTHCHECK Instruction",
      description: "Containers should define a health check so orchestrators can detect and restart unhealthy instances.",
      category: "operational",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "low",
      implementation_guidance: "Add `HEALTHCHECK` instruction to Dockerfile (e.g., `HEALTHCHECK --interval=30s CMD curl -f http://localhost:3000/health || exit 1`). In docker-compose, set `healthcheck:` block.",
      checks: [
        { id: "CIS-DOCKER-009-C1", description: "HEALTHCHECK instruction in Dockerfile", status: "not-implemented" },
        { id: "CIS-DOCKER-009-C2", description: "Health check configured in docker-compose", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-DOCKER-010",
      name: "Pin Image Digests (SHA256)",
      description: "Pin images by SHA256 digest instead of tags to guarantee the exact image content and prevent supply-chain attacks.",
      category: "supply-chain",
      framework: "CIS-DOCKER",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Use `image: node@sha256:abc123...` instead of `image: node:20-alpine`. Generate digests with `docker images --digests`. Pin all production images by digest in docker-compose and Kubernetes manifests.",
      checks: [
        { id: "CIS-DOCKER-010-C1", description: "Production images pinned by SHA256 digest", status: "not-implemented" },
        { id: "CIS-DOCKER-010-C2", description: "Digest verification in CI/CD", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "cis-docker",
    name: "CIS Docker Benchmark Policy Pack",
    description: "CIS Docker Benchmark controls for secure container configuration and deployment.",
    version: "1.0.0",
    project_types: [
      "saas", "api-backend", "generic-web-application", "ai-application",
      "healthcare-system", "government-system", "blockchain",
    ],
    controls,
    frameworks: ["CIS-DOCKER"],
  };
}
