import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createCISKubernetesPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "CIS-K8S-001",
      name: "API Server Uses RBAC",
      description: "The Kubernetes API server must use Role-Based Access Control (RBAC) to enforce least-privilege access.",
      category: "access-control",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Ensure `--authorization-mode` includes RBAC on the API server. Create specific Roles/RoleBindings with least privilege. Avoid ClusterRoleBindings with cluster-admin for service accounts. Audit RBAC policies regularly.",
      checks: [
        { id: "CIS-K8S-001-C1", description: "RBAC authorization mode enabled on API server", status: "not-implemented" },
        { id: "CIS-K8S-001-C2", description: "Least-privilege RoleBindings defined", status: "not-implemented" },
        { id: "CIS-K8S-001-C3", description: "No service accounts with cluster-admin", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-002",
      name: "API Server Not Exposed Publicly",
      description: "The Kubernetes API server should not be accessible from the public internet without VPN or bastion.",
      category: "network-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Use private cluster endpoints (e.g., AWS EKS private endpoint, GKE private cluster). Restrict API server access with authorized network ranges. Use a VPN or bastion host for administrative access.",
      checks: [
        { id: "CIS-K8S-002-C1", description: "API server endpoint is private", status: "not-implemented" },
        { id: "CIS-K8S-002-C2", description: "Authorized network restrictions configured", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-003",
      name: "etcd Encryption at Rest",
      description: "etcd (the Kubernetes data store) must have encryption at rest enabled to protect secrets stored in the cluster.",
      category: "encryption",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Enable encryption at rest with a KMS provider. Configure `--encryption-provider-config` on the API server. Use a managed KMS key (AWS KMS, GCP KMS, Azure Key Vault). Verify secrets are encrypted: `kubectl get secrets -o jsonpath='{.data}' | base64 -d`.",
      checks: [
        { id: "CIS-K8S-003-C1", description: "Encryption at rest enabled for etcd", status: "not-implemented" },
        { id: "CIS-K8S-003-C2", description: "KMS provider configured for key management", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-004",
      name: "Pod Security Standards Enforced",
      description: "Pod Security Standards (PSS) or Pod Security Policies must be enforced to prevent privileged containers and dangerous configurations.",
      category: "container-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Enable Pod Security Admission with at least `restricted` policy on production namespaces. Alternatively, use OPA Gatekeeper or Kyverno for policy enforcement. Block privileged pods, host namespaces, host paths, and root containers.",
      checks: [
        { id: "CIS-K8S-004-C1", description: "Pod Security Standards enforced (restricted profile)", status: "not-implemented" },
        { id: "CIS-K8S-004-C2", description: "Privileged containers blocked by policy", status: "not-implemented" },
        { id: "CIS-K8S-004-C3", description: "Host namespaces (PID, IPC, Network) blocked", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-005",
      name: "Network Policies Configured",
      description: "Network Policies must be defined to restrict pod-to-pod communication (micro-segmentation).",
      category: "network-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Install a CNI that supports NetworkPolicies (Calico, Cilium, Azure NPM). Define default-deny ingress and egress policies per namespace. Allow only required communication paths between services. Regularly audit policy coverage.",
      checks: [
        { id: "CIS-K8S-005-C1", description: "Default-deny network policy per namespace", status: "not-implemented" },
        { id: "CIS-K8S-005-C2", description: "Specific allow rules for required traffic", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-006",
      name: "Container Images from Trusted Registry",
      description: "All container images must come from a trusted, private registry — not public Docker Hub.",
      category: "supply-chain",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use a private container registry (ECR, GCR, ACR, Harbor). Configure image pull secrets. Scan images before pushing with Trivy/Grype. Enforce image provenance with OPA Gatekeeper or Kyverno admission controllers.",
      checks: [
        { id: "CIS-K8S-006-C1", description: "Images pulled from private trusted registry", status: "not-implemented" },
        { id: "CIS-K8S-006-C2", description: "Image scanning before deployment", status: "not-implemented" },
        { id: "CIS-K8S-006-C3", description: "Image pull secrets configured", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-007",
      name: "Run Pods as Non-Root",
      description: "Pods must run as a non-root user via securityContext.runAsNonRoot.",
      category: "container-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Set `securityContext.runAsNonRoot: true` and `securityContext.runAsUser: <non-zero-uid>` on all pods. Enforce via Pod Security Standards (restricted profile) or OPA Gatekeeper policies.",
      checks: [
        { id: "CIS-K8S-007-C1", description: "runAsNonRoot: true on all pods", status: "not-implemented" },
        { id: "CIS-K8S-007-C2", description: "runAsUser set to non-zero UID", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-008",
      name: "Read-Only Root Filesystem for Pods",
      description: "Pod containers should set readOnlyRootFilesystem to prevent writing to the container's root filesystem.",
      category: "container-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Set `securityContext.readOnlyRootFilesystem: true` on all containers. Mount emptyDir volumes for paths that need writes (/tmp, /var/cache). Enforce via Pod Security Standards restricted profile.",
      checks: [
        { id: "CIS-K8S-008-C1", description: "readOnlyRootFilesystem: true on all containers", status: "not-implemented" },
        { id: "CIS-K8S-008-C2", description: "Writable volumes mounted only where needed", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-009",
      name: "Resource Limits Defined",
      description: "All containers must define resource requests and limits for CPU and memory.",
      category: "resource-management",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Set `resources.requests` and `resources.limits` for CPU and memory on every container. Use LimitRange for namespace defaults. Use ResourceQuota to enforce total namespace limits. Monitor actual usage to tune values.",
      checks: [
        { id: "CIS-K8S-009-C1", description: "CPU and memory requests defined", status: "not-implemented" },
        { id: "CIS-K8S-009-C2", description: "CPU and memory limits defined", status: "not-implemented" },
        { id: "CIS-K8S-009-C3", description: "LimitRange default policy configured", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-010",
      name: "Audit Logging Enabled",
      description: "Kubernetes audit logging must be enabled to track all API server requests for security analysis.",
      category: "audit-logging",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Configure `--audit-log-path` and audit policy on the API server. Forward audit logs to a central log store (ELK, Loki, Splunk). Define audit rules for sensitive resources (secrets, RBAC, pods/exec). Retain logs per compliance requirements.",
      checks: [
        { id: "CIS-K8S-010-C1", description: "Audit logging enabled on API server", status: "not-implemented" },
        { id: "CIS-K8S-010-C2", description: "Audit policy defines rules for sensitive resources", status: "not-implemented" },
        { id: "CIS-K8S-010-C3", description: "Audit logs forwarded to central store", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-011",
      name: "Secrets Encrypted (KMS/Provider)",
      description: "Kubernetes Secrets should be encrypted using an external KMS provider, not stored in plaintext in etcd.",
      category: "encryption",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Configure a KMS encryption provider on the API server. Use AWS KMS, GCP KMS, or Azure Key Vault. Alternatively, use external secret management (External Secrets Operator with Vault, AWS Secrets Manager). Rotate encryption keys periodically.",
      checks: [
        { id: "CIS-K8S-011-C1", description: "KMS encryption provider configured", status: "not-implemented" },
        { id: "CIS-K8S-011-C2", description: "Encryption key rotation policy defined", status: "not-implemented" },
      ],
    },
    {
      id: "CIS-K8S-012",
      name: "Use securityContext",
      description: "All pods and containers must define a securityContext with appropriate security settings.",
      category: "container-security",
      framework: "CIS-K8S",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Define `securityContext` at both pod and container level. Include runAsNonRoot, runAsUser, fsGroup, capabilities.drop, seccompProfile, and allowPrivilegeEscalation: false. Validate via CI pipeline or admission webhook.",
      checks: [
        { id: "CIS-K8S-012-C1", description: "securityContext defined at pod level", status: "not-implemented" },
        { id: "CIS-K8S-012-C2", description: "securityContext defined at container level", status: "not-implemented" },
        { id: "CIS-K8S-012-C3", description: "allowPrivilegeEscalation: false set", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "cis-kubernetes",
    name: "CIS Kubernetes Benchmark Policy Pack",
    description: "CIS Kubernetes Benchmark controls for secure cluster configuration, pod security, and network policies.",
    version: "1.0.0",
    project_types: [
      "saas", "api-backend", "generic-web-application", "ai-application",
      "government-system", "blockchain",
    ],
    controls,
    frameworks: ["CIS-K8S"],
  };
}
