import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createHIPAAPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "HIPAA-164.308",
      name: "Administrative Safeguards",
      description: "Establish administrative policies and procedures to manage the selection, development, implementation, and maintenance of security measures for ePHI.",
      category: "security",
      framework: "HIPAA",
      article: "45 CFR 164.308",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Assign a Security Officer. Implement workforce security training. Establish access management procedures. Conduct periodic security evaluations. Maintain contingency plans.",
      checks: [
        { id: "HIPAA-164.308-C1", description: "Security Officer designated", status: "not-implemented" },
        { id: "HIPAA-164.308-C2", description: "Workforce security training program", status: "not-implemented" },
        { id: "HIPAA-164.308-C3", description: "Access management procedures documented", status: "not-implemented" },
        { id: "HIPAA-164.308-C4", description: "Periodic security evaluations conducted", status: "not-implemented" },
        { id: "HIPAA-164.308-C5", description: "Contingency plan established", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.310",
      name: "Physical Safeguards",
      description: "Implement physical policies and procedures to protect electronic information systems, related buildings, and equipment from unauthorized physical access.",
      category: "security",
      framework: "HIPAA",
      article: "45 CFR 164.310",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement facility access controls. Document device and media management procedures. Ensure workstation security. Maintain asset disposal procedures for media containing ePHI.",
      checks: [
        { id: "HIPAA-164.310-C1", description: "Facility access controls implemented", status: "not-implemented" },
        { id: "HIPAA-164.310-C2", description: "Workstation security policy documented", status: "not-implemented" },
        { id: "HIPAA-164.310-C3", description: "Device and media management procedures", status: "not-implemented" },
        { id: "HIPAA-164.310-C4", description: "Media disposal procedures documented", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.312-a",
      name: "Access Control",
      description: "Implement technical policies and procedures for electronic information systems that maintain ePHI to allow access only to those persons or software programs with appropriate access rights.",
      category: "authentication",
      framework: "HIPAA",
      article: "45 CFR 164.312(a)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement unique user identification. Enable automatic logoff. Implement encryption and decryption of ePHI. Use role-based access control with least privilege.",
      checks: [
        { id: "HIPAA-164.312-a-C1", description: "Unique user identification enforced", status: "not-implemented" },
        { id: "HIPAA-164.312-a-C2", description: "Automatic logoff configured", status: "not-implemented" },
        { id: "HIPAA-164.312-a-C3", description: "Encryption and decryption implemented for ePHI", status: "not-implemented" },
        { id: "HIPAA-164.312-a-C4", description: "Role-based access with least privilege", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.312-b",
      name: "Audit Controls",
      description: "Implement hardware, software, and procedural mechanisms that record and examine activity in information systems containing ePHI.",
      category: "audit",
      framework: "HIPAA",
      article: "45 CFR 164.312(b)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement comprehensive audit logging for all ePHI access. Log user ID, action, timestamp, resource accessed, and outcome. Protect logs from tampering. Review logs regularly.",
      checks: [
        { id: "HIPAA-164.312-b-C1", description: "Audit logging for all ePHI access", status: "not-implemented" },
        { id: "HIPAA-164.312-b-C2", description: "Logs include user action timestamp resource", status: "not-implemented" },
        { id: "HIPAA-164.312-b-C3", description: "Logs protected from tampering", status: "not-implemented" },
        { id: "HIPAA-164.312-b-C4", description: "Regular log review process", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.312-c",
      name: "Integrity Controls",
      description: "Implement policies and procedures to protect ePHI from improper alteration or destruction.",
      category: "security",
      framework: "HIPAA",
      article: "45 CFR 164.312(c)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement data integrity verification mechanisms. Use cryptographic hashing for ePHI. Detect unauthorized alterations. Maintain data integrity throughout lifecycle.",
      checks: [
        { id: "HIPAA-164.312-c-C1", description: "Data integrity verification implemented", status: "not-implemented" },
        { id: "HIPAA-164.312-c-C2", description: "Cryptographic hashing for ePHI integrity", status: "not-implemented" },
        { id: "HIPAA-164.312-c-C3", description: "Unauthorized alteration detection", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.312-d",
      name: "Person or Entity Authentication",
      description: "Implement procedures to verify that a person seeking access to ePHI is the one claimed.",
      category: "authentication",
      framework: "HIPAA",
      article: "45 CFR 164.312(d)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement strong authentication mechanisms. Use MFA for all ePHI system access. Verify identity before granting access. Maintain authentication audit trail.",
      checks: [
        { id: "HIPAA-164.312-d-C1", description: "Strong authentication mechanisms implemented", status: "not-implemented" },
        { id: "HIPAA-164.312-d-C2", description: "MFA for all ePHI system access", status: "not-implemented" },
        { id: "HIPAA-164.312-d-C3", description: "Authentication audit trail maintained", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.312-e",
      name: "Transmission Security",
      description: "Implement technical security measures to guard against unauthorized access to ePHI transmitted over electronic communications networks.",
      category: "encryption",
      framework: "HIPAA",
      article: "45 CFR 164.312(e)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Encrypt all ePHI in transit using TLS 1.2 or higher. Implement integrity controls for transmitted data. Verify endpoints before transmission. Use mutual TLS for system-to-system communication.",
      checks: [
        { id: "HIPAA-164.312-e-C1", description: "TLS 1.2 or higher for ePHI transmission", status: "not-implemented" },
        { id: "HIPAA-164.312-e-C2", description: "Integrity controls for transmitted data", status: "not-implemented" },
        { id: "HIPAA-164.312-e-C3", description: "Mutual TLS for system-to-system communication", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.314",
      name: "Business Associate Contracts",
      description: "Establish contracts with business associates that access ePHI to ensure they implement required safeguards.",
      category: "compliance",
      framework: "HIPAA",
      article: "45 CFR 164.314",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Execute Business Associate Agreements (BAAs) with all vendors accessing ePHI. Define permitted uses and disclosures. Include breach notification requirements. Terminate contracts on violation.",
      checks: [
        { id: "HIPAA-164.314-C1", description: "BAAs executed with all business associates", status: "not-implemented" },
        { id: "HIPAA-164.314-C2", description: "Permitted uses and disclosures defined", status: "not-implemented" },
        { id: "HIPAA-164.314-C3", description: "Breach notification requirements included", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.502",
      name: "Minimum Necessary Standard",
      description: "Limit access to and use of PHI to the minimum necessary to accomplish the intended purpose.",
      category: "compliance",
      framework: "HIPAA",
      article: "45 CFR 164.502(b)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement role-based access limiting PHI to minimum necessary. Define access levels by job function. Review and audit access patterns. Enforce field-level restrictions where applicable.",
      checks: [
        { id: "HIPAA-164.502-C1", description: "Minimum necessary access policies defined", status: "not-implemented" },
        { id: "HIPAA-164.502-C2", description: "Role-based access levels by job function", status: "not-implemented" },
        { id: "HIPAA-164.502-C3", description: "Access pattern auditing implemented", status: "not-implemented" },
      ],
    },
    {
      id: "HIPAA-164.530",
      name: "Administrative Requirements",
      description: "Implement administrative requirements for privacy including designated privacy officer, training, and complaint procedures.",
      category: "compliance",
      framework: "HIPAA",
      article: "45 CFR 164.530",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Designate a Privacy Officer. Implement privacy training for all workforce members. Establish complaint procedures. Maintain documentation of privacy policies and procedures for at least 6 years.",
      checks: [
        { id: "HIPAA-164.530-C1", description: "Privacy Officer designated", status: "not-implemented" },
        { id: "HIPAA-164.530-C2", description: "Privacy training program implemented", status: "not-implemented" },
        { id: "HIPAA-164.530-C3", description: "Complaint procedures established", status: "not-implemented" },
        { id: "HIPAA-164.530-C4", description: "Documentation retained for 6 years minimum", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "hipaa",
    name: "HIPAA Healthcare Policy Pack",
    description: "HIPAA Security Rule and Privacy Rule controls for healthcare systems handling electronic Protected Health Information (ePHI).",
    version: "1.0.0",
    project_types: [
      "healthcare-system", "saas",
    ],
    controls,
    frameworks: ["HIPAA"],
  };
}
