import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createNIST80053PolicyPack(): PolicyPack {
  const controls: Control[] = [

    // ============================================================
    // AC — ACCESS CONTROL
    // ============================================================

    {
      id: "NIST-800-53-AC-2",
      name: "Account Management",
      description: "Manage system accounts, establish account types, and monitor active accounts.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement an account management system that creates, enables, modifies, disables, and removes accounts. Define account types (individual, shared, group, system, guest/anonymous, temporary). Notify account managers when accounts are no longer required. Authorize and monitor guest/anonymous and temporary accounts. Disable inactive accounts within 35 days. Monitor for repeated unauthorized access attempts.",
      checks: [
        { id: "NIST-800-53-AC-2-C1", description: "Account management procedures documented and enforced", status: "not-implemented" },
        { id: "NIST-800-53-AC-2-C2", description: "Account types defined with role-based assignments", status: "not-implemented" },
        { id: "NIST-800-53-AC-2-C3", description: "Inactive accounts disabled within 35 days", status: "not-implemented" },
        { id: "NIST-800-53-AC-2-C4", description: "Account managers notified of account changes", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-3",
      name: "Access Enforcement",
      description: "Enforce approved authorizations for logical access to system resources in accordance with applicable access control policies.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Enforce access control policies through technical safeguards such as role-based access control (RBAC), attribute-based access control (ABAC), or mandatory access control (MAC). Ensure the system uniquely identifies and authenticates users before granting access. Deny access by default; allow only explicitly authorized access.",
      checks: [
        { id: "NIST-800-53-AC-3-C1", description: "Access control model (RBAC/ABAC/MAC) implemented and enforced", status: "not-implemented" },
        { id: "NIST-800-53-AC-3-C2", description: "Default-deny policy enforced on all protected resources", status: "not-implemented" },
        { id: "NIST-800-53-AC-3-C3", description: "Access decisions logged for audit", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-5",
      name: "Separation of Duties",
      description: "Separate duties of individuals to prevent malevolent activity without collusion.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Identify and document functions that require separation of duties. Define access authorizations to support separation of duties. Ensure separation of duties is enforced through technical controls where feasible (e.g., require two-person approval for privileged operations).",
      checks: [
        { id: "NIST-800-53-AC-5-C1", description: "Critical functions requiring separation of duties identified", status: "not-implemented" },
        { id: "NIST-800-53-AC-5-C2", description: "Technical controls enforce separation of duties", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-6",
      name: "Least Privilege",
      description: "Grant only the access necessary to accomplish assigned tasks in accordance with organizational missions and business functions.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Design systems to enforce least privilege. Implement privileged access management (PAM) for admin accounts. Periodically review privileged access assignments (at least annually). Authorize access for privileged accounts for limited timeframes (just-in-time access). Re-evaluate access when duties change.",
      checks: [
        { id: "NIST-800-53-AC-6-C1", description: "Least privilege enforced through role-based assignments", status: "not-implemented" },
        { id: "NIST-800-53-AC-6-C2", description: "Privileged access reviewed at least annually", status: "not-implemented" },
        { id: "NIST-800-53-AC-6-C3", description: "Just-in-time access for high-privilege operations", status: "not-implemented" },
        { id: "NIST-800-53-AC-6-C4", description: "Privileged access management (PAM) solution deployed", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-7",
      name: "Unsuccessful Logon Attempts",
      description: "Enforce limit on consecutive invalid logon attempts and automatically lock the account.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Enforce a limit of no more than 3 consecutive invalid logon attempts. Automatically lock the account/node for a defined period (recommended: minimum 15 minutes or until administrator unlocks). Log all unsuccessful logon attempts and alert on patterns indicating brute-force attacks.",
      checks: [
        { id: "NIST-800-53-AC-7-C1", description: "Account lockout after 3 invalid attempts enforced", status: "not-implemented" },
        { id: "NIST-800-53-AC-7-C2", description: "Lockout period configured (min 15 minutes)", status: "not-implemented" },
        { id: "NIST-800-53-AC-7-C3", description: "Brute-force patterns trigger security alerts", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-11",
      name: "Session Lock",
      description: "Lock sessions after a defined period of inactivity and require re-authentication to unlock.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Initiate a session lock after 15 minutes of inactivity. Retain the session lock until re-authentication occurs. Hide the session contents (blank screen or obfuscation) when locked. Allow users to manually initiate session lock.",
      checks: [
        { id: "NIST-800-53-AC-11-C1", description: "Automatic session lock after 15 min inactivity", status: "not-implemented" },
        { id: "NIST-800-53-AC-11-C2", description: "Session contents hidden when locked", status: "not-implemented" },
        { id: "NIST-800-53-AC-11-C3", description: "Manual session lock available", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-17",
      name: "Remote Access",
      description: "Authorize, monitor, and control remote access to systems.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Establish and document remote access usage policies. Enforce multi-factor authentication for all remote access. Encrypt all remote access sessions (TLS 1.2+, VPN). Monitor and log all remote access sessions. Automatically terminate remote access sessions after a defined period. Route remote access through managed access control points.",
      checks: [
        { id: "NIST-800-53-AC-17-C1", description: "Remote access policy documented", status: "not-implemented" },
        { id: "NIST-800-53-AC-17-C2", description: "MFA enforced on all remote access", status: "not-implemented" },
        { id: "NIST-800-53-AC-17-C3", description: "All remote sessions encrypted and logged", status: "not-implemented" },
        { id: "NIST-800-53-AC-17-C4", description: "Remote access routed through controlled access points", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AC-20",
      name: "Use of External Systems",
      description: "Establish terms and conditions for use of external systems and control use of organization-controlled systems on external networks.",
      category: "access-control",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Establish terms and conditions for use of external systems. Prohibit processing, storage, or transmission of CUI on external systems unless approved. Require security assessments of external systems before use. Implement full-device or container-based encryption for mobile devices.",
      checks: [
        { id: "NIST-800-53-AC-20-C1", description: "Terms and conditions for external systems documented", status: "not-implemented" },
        { id: "NIST-800-53-AC-20-C2", description: "CUI processing on external systems restricted", status: "not-implemented" },
        { id: "NIST-800-53-AC-20-C3", description: "Mobile devices encrypted (full-device or container)", status: "not-implemented" },
      ],
    },

    // ============================================================
    // AT — AWARENESS AND TRAINING
    // ============================================================

    {
      id: "NIST-800-53-AT-2",
      name: "Literacy Training and Awareness",
      description: "Provide security and privacy literacy training to system users on initial hire and at least annually thereafter.",
      category: "training",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Provide security awareness training upon hire and at least annually. Include content on recognizing phishing, social engineering, malware indicators, and proper handling of CUI. Update training content to reflect new threats. Track completion and provide refresher training as needed.",
      checks: [
        { id: "NIST-800-53-AT-2-C1", description: "Security awareness training provided on hire", status: "not-implemented" },
        { id: "NIST-800-53-AT-2-C2", description: "Annual refresher training completed by all personnel", status: "not-implemented" },
        { id: "NIST-800-53-AT-2-C3", description: "Training includes phishing and social engineering awareness", status: "not-implemented" },
        { id: "NIST-800-53-AT-2-C4", description: "Training completion tracked and reported", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AT-3",
      name: "Role-Based Training",
      description: "Provide role-based security and privacy training to personnel with specialized responsibilities.",
      category: "training",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Identify roles requiring specialized training (system admins, security officers, developers, incident responders). Provide practical, hands-on training specific to each role. Include training on secure coding practices for developers and incident response procedures for security teams.",
      checks: [
        { id: "NIST-800-53-AT-3-C1", description: "Specialized roles requiring role-based training identified", status: "not-implemented" },
        { id: "NIST-800-53-AT-3-C2", description: "Hands-on training provided for each identified role", status: "not-implemented" },
        { id: "NIST-800-53-AT-3-C3", description: "Training updated to reflect current threat landscape", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AT-4",
      name: "Training Records",
      description: "Document and monitor security and privacy training activities including completion and content.",
      category: "training",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "low",
      implementation_guidance: "Maintain records of all training activities including who was trained, when, what content was delivered, and completion status. Retain training records for at least the duration of employment. Use a learning management system (LMS) for tracking.",
      checks: [
        { id: "NIST-800-53-AT-4-C1", description: "Training records maintained with completion status", status: "not-implemented" },
        { id: "NIST-800-53-AT-4-C2", description: "Records retained per organization retention policy", status: "not-implemented" },
      ],
    },

    // ============================================================
    // AU — AUDIT AND ACCOUNTABILITY
    // ============================================================

    {
      id: "NIST-800-53-AU-2",
      name: "Event Logging",
      description: "Identify and log security-relevant events on the system.",
      category: "audit",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Identify the types of events to be logged (authentication successes/failures, privilege escalations, configuration changes, data access, policy changes). Coordinate with other entities to enable correlation. Log events from all system components including applications, databases, network devices, and operating systems.",
      checks: [
        { id: "NIST-800-53-AU-2-C1", description: "Security-relevant event types identified and documented", status: "not-implemented" },
        { id: "NIST-800-53-AU-2-C2", description: "Event logging enabled on all system components", status: "not-implemented" },
        { id: "NIST-800-53-AU-2-C3", description: "Logs support cross-system event correlation", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AU-3",
      name: "Content of Audit Records",
      description: "Ensure audit records contain sufficient information to establish what, when, where, who, and outcome.",
      category: "audit",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Ensure audit records contain: date/time stamp, source IP address, user/subject identity, event type, event outcome (success/failure), resource/object accessed, and session identifier. Use a centralized logging format (e.g., JSON, CEF) for consistency.",
      checks: [
        { id: "NIST-800-53-AU-3-C1", description: "Audit records include timestamp, user, action, resource, outcome", status: "not-implemented" },
        { id: "NIST-800-53-AU-3-C2", description: "Source IP and session ID captured in records", status: "not-implemented" },
        { id: "NIST-800-53-AU-3-C3", description: "Centralized log format used for consistency", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AU-6",
      name: "Audit Record Review, Analysis, and Reporting",
      description: "Integrate audit record review, analysis, and reporting for investigation of security and privacy incidents.",
      category: "audit",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Review and analyze audit records on a regular basis (at least weekly). Integrate audit record monitoring with intrusion detection and SIEM systems. Use automated tools for log analysis and anomaly detection. Report findings to appropriate personnel and escalate anomalies.",
      checks: [
        { id: "NIST-800-53-AU-6-C1", description: "Audit records reviewed at least weekly", status: "not-implemented" },
        { id: "NIST-800-53-AU-6-C2", description: "Log analysis integrated with SIEM/SOC", status: "not-implemented" },
        { id: "NIST-800-53-AU-6-C3", description: "Anomalies reported and escalated to security team", status: "not-implemented" },
        { id: "NIST-800-53-AU-6-C4", description: "Automated anomaly detection deployed", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AU-9",
      name: "Protection of Audit Information",
      description: "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
      category: "audit",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Protect audit information using access controls, encryption at rest, and WORM (write-once-read-many) storage where possible. Restrict access to audit tools to authorized personnel only. Store audit logs on a separate system or in a centralized log management system to prevent tampering.",
      checks: [
        { id: "NIST-800-53-AU-9-C1", description: "Audit logs protected by access controls", status: "not-implemented" },
        { id: "NIST-800-53-AU-9-C2", description: "Audit logs encrypted at rest", status: "not-implemented" },
        { id: "NIST-800-53-AU-9-C3", description: "Access to audit tools restricted to authorized personnel", status: "not-implemented" },
        { id: "NIST-800-53-AU-9-C4", description: "Logs stored on separate/tamper-resistant system", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-AU-12",
      name: "Audit Record Generation",
      description: "Provide audit record generation capability for security-relevant events.",
      category: "audit",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Generate audit records for all identified security-relevant events. Compile records from various system components into a system-wide audit trail. Provide audit records to a centralized audit repository. Verify audit record generation is functioning correctly through periodic testing.",
      checks: [
        { id: "NIST-800-53-AU-12-C1", description: "Audit records generated for all defined events", status: "not-implemented" },
        { id: "NIST-800-53-AU-12-C2", description: "Records compiled into system-wide audit trail", status: "not-implemented" },
        { id: "NIST-800-53-AU-12-C3", description: "Records forwarded to centralized repository", status: "not-implemented" },
      ],
    },

    // ============================================================
    // CA — ASSESSMENT, AUTHORIZATION, AND MONITORING
    // ============================================================

    {
      id: "NIST-800-53-CA-2",
      name: "Control Assessment",
      description: "Assess the security and privacy controls in the system to determine effectiveness.",
      category: "assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop a security and privacy assessment plan. Assess controls upon initial implementation and at least annually thereafter. Use independent assessors (internal or external). Produce an assessment report documenting findings. Remediate identified deficiencies.",
      checks: [
        { id: "NIST-800-53-CA-2-C1", description: "Assessment plan developed and documented", status: "not-implemented" },
        { id: "NIST-800-53-CA-2-C2", description: "Controls assessed at least annually", status: "not-implemented" },
        { id: "NIST-800-53-CA-2-C3", description: "Assessment report produced with remediation plan", status: "not-implemented" },
        { id: "NIST-800-53-CA-2-C4", description: "Independent assessors used", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CA-7",
      name: "Continuous Monitoring",
      description: "Develop a system-level continuous monitoring strategy and implement continuous monitoring.",
      category: "assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop a continuous monitoring strategy that includes: configuration management, security control assessments, network monitoring, vulnerability scanning, and threat intelligence integration. Determine the frequency of monitoring based on risk. Report findings monthly/quarterly to authorizing officials.",
      checks: [
        { id: "NIST-800-53-CA-7-C1", description: "Continuous monitoring strategy documented", status: "not-implemented" },
        { id: "NIST-800-53-CA-7-C2", description: "Automated monitoring tools deployed", status: "not-implemented" },
        { id: "NIST-800-53-CA-7-C3", description: "Monitoring results reported to authorizing officials", status: "not-implemented" },
        { id: "NIST-800-53-CA-7-C4", description: "Monitoring frequency based on risk assessment", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CA-9",
      name: "Internal System Connections",
      description: "Authorize internal connections of system components or subsystems.",
      category: "assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Document each internal system connection including the interface characteristics, security requirements, and the nature of information communicated. Authorize each connection before implementation. Review and re-authorize connections annually. Monitor connections for unauthorized changes.",
      checks: [
        { id: "NIST-800-53-CA-9-C1", description: "Internal system connections documented and authorized", status: "not-implemented" },
        { id: "NIST-800-53-CA-9-C2", description: "Connections reviewed and re-authorized annually", status: "not-implemented" },
      ],
    },

    // ============================================================
    // CM — CONFIGURATION MANAGEMENT
    // ============================================================

    {
      id: "NIST-800-53-CM-2",
      name: "Baseline Configuration",
      description: "Develop, document, and maintain a current baseline configuration of the system.",
      category: "configuration-management",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Establish and document baseline configurations for hardware, software, operating systems, and application components. Review and update baselines at least annually or after significant changes. Use infrastructure-as-code (IaC) to maintain baseline configurations. Implement automated configuration drift detection.",
      checks: [
        { id: "NIST-800-53-CM-2-C1", description: "Baseline configurations documented for all components", status: "not-implemented" },
        { id: "NIST-800-53-CM-2-C2", description: "Baselines reviewed and updated at least annually", status: "not-implemented" },
        { id: "NIST-800-53-CM-2-C3", description: "Infrastructure-as-code used to maintain baselines", status: "not-implemented" },
        { id: "NIST-800-53-CM-2-C4", description: "Configuration drift detection implemented", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CM-3",
      name: "Configuration Change Control",
      description: "Determine and document the types of changes to the system that are configuration-controlled.",
      category: "configuration-management",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Approve and document configuration changes through a formal change control board (CCB) or equivalent process. Retain records of changes for audit. Review and test changes before deployment. Implement automated CI/CD pipelines with security gates.",
      checks: [
        { id: "NIST-800-53-CM-3-C1", description: "Change control process documented and enforced", status: "not-implemented" },
        { id: "NIST-800-53-CM-3-C2", description: "Change records retained for audit", status: "not-implemented" },
        { id: "NIST-800-53-CM-3-C3", description: "Changes tested before deployment", status: "not-implemented" },
        { id: "NIST-800-53-CM-3-C4", description: "CI/CD pipelines include security gates", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CM-6",
      name: "Configuration Settings",
      description: "Establish, document, and implement secure configuration settings for system components.",
      category: "configuration-management",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Establish security configuration settings based on CIS Benchmarks, DISA STIGs, or vendor hardening guides. Document and implement settings. Enforce settings through automated tools (e.g., Group Policy, Ansible, Chef). Monitor for deviations and remediate.",
      checks: [
        { id: "NIST-800-53-CM-6-C1", description: "Secure configuration settings documented (CIS/STIG)", status: "not-implemented" },
        { id: "NIST-800-53-CM-6-C2", description: "Settings enforced through automation", status: "not-implemented" },
        { id: "NIST-800-53-CM-6-C3", description: "Deviations monitored and remediated", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CM-7",
      name: "Least Functionality",
      description: "Configure the system with only essential functions, ports, protocols, and services.",
      category: "configuration-management",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Identify and document essential functions, ports, protocols, and services. Disable, remove, or restrict non-essential capabilities. Implement software allow-listing where feasible. Review functionality at least annually to identify and remove unnecessary components.",
      checks: [
        { id: "NIST-800-53-CM-7-C1", description: "Essential functions, ports, and services documented", status: "not-implemented" },
        { id: "NIST-800-53-CM-7-C2", description: "Non-essential capabilities disabled or removed", status: "not-implemented" },
        { id: "NIST-800-53-CM-7-C3", description: "Software allow-listing implemented", status: "not-implemented" },
        { id: "NIST-800-53-CM-7-C4", description: "Functionality reviewed annually", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CM-8",
      name: "System Component Inventory",
      description: "Develop and document an inventory of system components that accurately reflects the current system.",
      category: "configuration-management",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Maintain an automated inventory of all system components including hardware, software, firmware, and network assets. Include component details: manufacturer, model, serial number, software versions, location, and owner. Update inventory automatically (agent-based or agentless discovery). Verify inventory at least monthly.",
      checks: [
        { id: "NIST-800-53-CM-8-C1", description: "Automated asset inventory maintained", status: "not-implemented" },
        { id: "NIST-800-53-CM-8-C2", description: "Inventory includes all required component details", status: "not-implemented" },
        { id: "NIST-800-53-CM-8-C3", description: "Inventory verified at least monthly", status: "not-implemented" },
        { id: "NIST-800-53-CM-8-C4", description: "Inventory integrated with configuration management", status: "not-implemented" },
      ],
    },

    // ============================================================
    // CP — CONTINGENCY PLANNING
    // ============================================================

    {
      id: "NIST-800-53-CP-2",
      name: "Contingency Plan",
      description: "Develop, document, and maintain a contingency plan for the system.",
      category: "contingency-planning",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop a contingency plan that includes: roles and responsibilities, recovery objectives (RTO/RPO), recovery procedures, and essential records. Review and update the plan at least annually. Distribute copies to key personnel. Coordinate the plan with related plans (incident response, business continuity).",
      checks: [
        { id: "NIST-800-53-CP-2-C1", description: "Contingency plan documented with RTO/RPO", status: "not-implemented" },
        { id: "NIST-800-53-CP-2-C2", description: "Plan reviewed and updated at least annually", status: "not-implemented" },
        { id: "NIST-800-53-CP-2-C3", description: "Plan distributed to key personnel", status: "not-implemented" },
        { id: "NIST-800-53-CP-2-C4", description: "Plan coordinated with IR and BC plans", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CP-9",
      name: "System Backup",
      description: "Conduct backups of user-level and system-level information consistent with recovery objectives.",
      category: "contingency-planning",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Conduct daily backups of user-level and system-level information. Protect backup information with encryption. Store backup copies in a physically separate facility or cloud region. Test backup information at least quarterly to verify media reliability and information integrity.",
      checks: [
        { id: "NIST-800-53-CP-9-C1", description: "Daily backups performed for all critical data", status: "not-implemented" },
        { id: "NIST-800-53-CP-9-C2", description: "Backups encrypted at rest", status: "not-implemented" },
        { id: "NIST-800-53-CP-9-C3", description: "Backups stored in separate facility/region", status: "not-implemented" },
        { id: "NIST-800-53-CP-9-C4", description: "Backups tested at least quarterly", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-CP-10",
      name: "System Recovery and Reconstitution",
      description: "Provide for the recovery and reconstitution of the system to a known state after a disruption, compromise, or failure.",
      category: "contingency-planning",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement recovery procedures that restore the system to a known, secure state. Include procedures for restoring from backup, verifying system integrity, and reconstituting services. Test recovery procedures annually. Maintain an alternate communications capability for recovery coordination.",
      checks: [
        { id: "NIST-800-53-CP-10-C1", description: "Recovery procedures documented and tested", status: "not-implemented" },
        { id: "NIST-800-53-CP-10-C2", description: "System integrity verification after recovery", status: "not-implemented" },
        { id: "NIST-800-53-CP-10-C3", description: "Annual recovery testing conducted", status: "not-implemented" },
      ],
    },

    // ============================================================
    // IA — IDENTIFICATION AND AUTHENTICATION
    // ============================================================

    {
      id: "NIST-800-53-IA-2",
      name: "Identification and Authentication",
      description: "Uniquely identify and authenticate system users and processes.",
      category: "authentication",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Uniquely identify and authenticate all users. Implement multi-factor authentication (MFA) for all accounts including: privileged accounts, remote access, and all non-organizational users. Use phishing-resistant MFA where feasible (FIDO2, WebAuthn). Implement MFA for all network access to privileged and non-privileged accounts.",
      checks: [
        { id: "NIST-800-53-IA-2-C1", description: "All users uniquely identified", status: "not-implemented" },
        { id: "NIST-800-53-IA-2-C2", description: "MFA enforced for privileged accounts", status: "not-implemented" },
        { id: "NIST-800-53-IA-2-C3", description: "MFA enforced for remote access", status: "not-implemented" },
        { id: "NIST-800-53-IA-2-C4", description: "Phishing-resistant MFA (FIDO2/WebAuthn) available", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-IA-5",
      name: "Authenticator Management",
      description: "Manage system authenticators by verifying, protecting, and controlling them.",
      category: "authentication",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Define initial authenticator content and establish minimum authenticator strength requirements (NIST SP 800-63B). Protect authenticators from unauthorized disclosure and modification. Change default authenticators upon installation. Enforce password policies: minimum length 12+, no composition rules, screening against compromised password lists. Expire or revoke authenticators when no longer needed.",
      checks: [
        { id: "NIST-800-53-IA-5-C1", description: "Authenticator strength requirements defined", status: "not-implemented" },
        { id: "NIST-800-53-IA-5-C2", description: "Default credentials changed on installation", status: "not-implemented" },
        { id: "NIST-800-53-IA-5-C3", description: "Password policy aligned with NIST SP 800-63B", status: "not-implemented" },
        { id: "NIST-800-53-IA-5-C4", description: "Compromised password screening implemented", status: "not-implemented" },
        { id: "NIST-800-53-IA-5-C5", description: "Authenticators revoked when access is no longer needed", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-IA-8",
      name: "Service Provider Identification and Authentication",
      description: "Uniquely identify and authenticate non-organizational (service provider) systems and processes.",
      category: "authentication",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Identify and authenticate systems/services acting on behalf of external organizations. Implement machine-to-machine authentication using certificates, API keys with rotation, or OAuth 2.0 client credentials. Log and monitor service provider access.",
      checks: [
        { id: "NIST-800-53-IA-8-C1", description: "Service provider authentication implemented", status: "not-implemented" },
        { id: "NIST-800-53-IA-8-C2", description: "Machine-to-machine auth uses certificates or OAuth", status: "not-implemented" },
        { id: "NIST-800-53-IA-8-C3", description: "Service provider access logged and monitored", status: "not-implemented" },
      ],
    },

    // ============================================================
    // IR — INCIDENT RESPONSE
    // ============================================================

    {
      id: "NIST-800-53-IR-4",
      name: "Incident Handling",
      description: "Implement an incident handling capability for security and privacy incidents.",
      category: "incident-response",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement an incident handling capability aligned with NIST SP 800-61 covering detection, analysis, containment, eradication, and recovery. Execute incident handling procedures in coordination with contingency plans. Incorporate lessons learned from incidents into procedures and controls.",
      checks: [
        { id: "NIST-800-53-IR-4-C1", description: "Incident response procedures documented (NIST SP 800-61)", status: "not-implemented" },
        { id: "NIST-800-53-IR-4-C2", description: "IR procedures coordinate with contingency planning", status: "not-implemented" },
        { id: "NIST-800-53-IR-4-C3", description: "Lessons learned incorporated into procedures", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-IR-5",
      name: "Incident Monitoring",
      description: "Track and document security and privacy incidents.",
      category: "incident-response",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Track and document incidents from initial detection through final resolution. Use an incident management/ticketing system. Include key details: detection time, classification, scope, actions taken, and resolution. Generate monthly reports on incident metrics and trends.",
      checks: [
        { id: "NIST-800-53-IR-5-C1", description: "Incident tracking system deployed", status: "not-implemented" },
        { id: "NIST-800-53-IR-5-C2", description: "Incidents tracked from detection to resolution", status: "not-implemented" },
        { id: "NIST-800-53-IR-5-C3", description: "Monthly incident metrics reported", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-IR-6",
      name: "Incident Reporting",
      description: "Report security and privacy incidents to designated organizational authorities and external organizations.",
      category: "incident-response",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Report confirmed incidents to organizational authorities (CISO, legal, privacy officer) within defined timeframes. Report qualifying incidents to external organizations (US-CERT, law enforcement, regulatory bodies) as required. Establish automated alerting for critical incidents. Document reporting requirements and procedures.",
      checks: [
        { id: "NIST-800-53-IR-6-C1", description: "Incident reporting procedures documented", status: "not-implemented" },
        { id: "NIST-800-53-IR-6-C2", description: "Internal reporting timeframes defined and met", status: "not-implemented" },
        { id: "NIST-800-53-IR-6-C3", description: "External reporting (US-CERT/regulators) when required", status: "not-implemented" },
        { id: "NIST-800-53-IR-6-C4", description: "Automated alerting for critical incidents", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-IR-8",
      name: "Incident Response Plan",
      description: "Develop and disseminate an incident response plan.",
      category: "incident-response",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop a formal incident response plan that includes: mission, roles and responsibilities, performance measures, and communication plan. Disseminate the plan to all incident response personnel. Review and update at least annually. Test the plan annually via tabletop exercises or simulations.",
      checks: [
        { id: "NIST-800-53-IR-8-C1", description: "IR plan documented with roles and communication procedures", status: "not-implemented" },
        { id: "NIST-800-53-IR-8-C2", description: "Plan disseminated to IR team members", status: "not-implemented" },
        { id: "NIST-800-53-IR-8-C3", description: "Plan tested annually (tabletop or simulation)", status: "not-implemented" },
        { id: "NIST-800-53-IR-8-C4", description: "Plan reviewed and updated at least annually", status: "not-implemented" },
      ],
    },

    // ============================================================
    // MA — MAINTENANCE
    // ============================================================

    {
      id: "NIST-800-53-MA-2",
      name: "Controlled Maintenance",
      description: "Schedule, document, and review maintenance for systems and system components.",
      category: "maintenance",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Schedule and approve all maintenance through formal processes. Include maintenance records: date, time, description of maintenance, personnel involved, and system components affected. Review maintenance records and inspect systems for unauthorized changes after maintenance. Require sanitization of equipment removed for off-site maintenance.",
      checks: [
        { id: "NIST-800-53-MA-2-C1", description: "Maintenance scheduling and approval process documented", status: "not-implemented" },
        { id: "NIST-800-53-MA-2-C2", description: "Maintenance records maintained with full details", status: "not-implemented" },
        { id: "NIST-800-53-MA-2-C3", description: "Post-maintenance inspections conducted", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-MA-4",
      name: "Nonlocal Maintenance",
      description: "Authorize, monitor, and control nonlocal maintenance and diagnostic activities.",
      category: "maintenance",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Approve and document all nonlocal maintenance activities. Use multi-factor authentication and encryption for nonlocal maintenance sessions. Terminate sessions automatically after a defined period. Monitor nonlocal maintenance sessions and log all activity. Scan remote diagnostic tools for malware before use.",
      checks: [
        { id: "NIST-800-53-MA-4-C1", description: "Nonlocal maintenance approved and documented", status: "not-implemented" },
        { id: "NIST-800-53-MA-4-C2", description: "MFA and encryption enforced for remote maintenance", status: "not-implemented" },
        { id: "NIST-800-53-MA-4-C3", description: "Sessions auto-terminate after defined period", status: "not-implemented" },
        { id: "NIST-800-53-MA-4-C4", description: "All sessions logged and monitored", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-MA-6",
      name: "Timely Maintenance",
      description: "Initiate maintenance and correct defects in system components within specified timeframes.",
      category: "maintenance",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Define maintenance timeframes based on severity of defects (critical: within 48 hours, high: within 7 days, medium: within 30 days). Track maintenance tickets through completion. Escalate overdue maintenance items. Maintain spare or replacement components to minimize downtime.",
      checks: [
        { id: "NIST-800-53-MA-6-C1", description: "Maintenance timeframes defined by severity", status: "not-implemented" },
        { id: "NIST-800-53-MA-6-C2", description: "Maintenance tracked through completion", status: "not-implemented" },
        { id: "NIST-800-53-MA-6-C3", description: "Overdue items escalated", status: "not-implemented" },
      ],
    },

    // ============================================================
    // MP — MEDIA PROTECTION
    // ============================================================

    {
      id: "NIST-800-53-MP-4",
      name: "Media Storage",
      description: "Protect and control physical media containing sensitive information.",
      category: "media-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Store physical media (USB drives, tapes, hard drives, optical media) in secure, access-controlled locations. Protect media from environmental damage (fire, water, temperature). Implement an inventory system for media containing CUI. Restrict access to media to authorized personnel only.",
      checks: [
        { id: "NIST-800-53-MP-4-C1", description: "Physical media stored in secure location", status: "not-implemented" },
        { id: "NIST-800-53-MP-4-C2", description: "Media protected from environmental damage", status: "not-implemented" },
        { id: "NIST-800-53-MP-4-C3", description: "CUI media inventoried and tracked", status: "not-implemented" },
        { id: "NIST-800-53-MP-4-C4", description: "Access to media restricted to authorized personnel", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-MP-6",
      name: "Media Sanitization",
      description: "Sanitize media prior to disposal, release out of organizational control, or release for reuse.",
      category: "media-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Sanitize media using methods approved by NIST SP 800-88 (Clear, Purge, or Destroy). Document sanitization actions including: media type, sanitization method, date, and personnel. Verify sanitization effectiveness. Use cryptographic erase for encrypted storage. Employ physical destruction (shredding, crushing, incineration) for media that cannot be securely erased.",
      checks: [
        { id: "NIST-800-53-MP-6-C1", description: "Sanitization procedures documented (NIST SP 800-88)", status: "not-implemented" },
        { id: "NIST-800-53-MP-6-C2", description: "Sanitization actions documented and verified", status: "not-implemented" },
        { id: "NIST-800-53-MP-6-C3", description: "Physical destruction used when secure erase not possible", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-MP-7",
      name: "Media Use",
      description: "Restrict or prohibit use of system media and enforce encryption on mobile devices.",
      category: "media-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Restrict the use of removable media (USB, external drives) through technical controls. Encrypt all data on mobile devices and removable media. Prohibit use of personally-owned removable media. Use data loss prevention (DLP) tools to monitor and control data transfers.",
      checks: [
        { id: "NIST-800-53-MP-7-C1", description: "Removable media usage restricted through policy", status: "not-implemented" },
        { id: "NIST-800-53-MP-7-C2", description: "Full-disk encryption on mobile devices", status: "not-implemented" },
        { id: "NIST-800-53-MP-7-C3", description: "DLP tools deployed to control data transfers", status: "not-implemented" },
      ],
    },

    // ============================================================
    // PE — PHYSICAL AND ENVIRONMENTAL PROTECTION
    // ============================================================

    {
      id: "NIST-800-53-PE-2",
      name: "Physical Access Authorizations",
      description: "Develop, approve, and maintain a list of individuals with physical access to the facility.",
      category: "physical-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Maintain a current list of personnel authorized for physical access to facilities containing systems. Review authorization lists at least annually. Remove access for terminated or transferred personnel within 24 hours. Issue and control physical access badges/credentials.",
      checks: [
        { id: "NIST-800-53-PE-2-C1", description: "Physical access authorization list maintained", status: "not-implemented" },
        { id: "NIST-800-53-PE-2-C2", description: "List reviewed at least annually", status: "not-implemented" },
        { id: "NIST-800-53-PE-2-C3", description: "Terminated personnel access removed within 24h", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PE-3",
      name: "Physical Access Control",
      description: "Implement physical access control devices/procedures to safeguard the facility and system components.",
      category: "physical-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Verify individual physical access before granting facility access. Control physical access points including gates, doors, and loading docks. Escort visitors and monitor visitor activity. Maintain physical access audit logs. Secure output devices (printers) to prevent unauthorized document removal. Implement intrusion detection and video surveillance.",
      checks: [
        { id: "NIST-800-53-PE-3-C1", description: "Physical access verified before granting entry", status: "not-implemented" },
        { id: "NIST-800-53-PE-3-C2", description: "Visitors escorted and monitored", status: "not-implemented" },
        { id: "NIST-800-53-PE-3-C3", description: "Physical access logs maintained", status: "not-implemented" },
        { id: "NIST-800-53-PE-3-C4", description: "Intrusion detection and video surveillance deployed", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PE-6",
      name: "Monitoring Physical Access",
      description: "Monitor physical access to the facility and investigate unauthorized physical access.",
      category: "physical-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Monitor physical intrusion alarms and surveillance equipment. Review physical access logs at least monthly. Investigate and report unauthorized physical access attempts. Coordinate monitoring with internal security personnel or external monitoring services.",
      checks: [
        { id: "NIST-800-53-PE-6-C1", description: "Intrusion alarms and surveillance monitored", status: "not-implemented" },
        { id: "NIST-800-53-PE-6-C2", description: "Access logs reviewed monthly", status: "not-implemented" },
        { id: "NIST-800-53-PE-6-C3", description: "Unauthorized access investigated and reported", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PE-16",
      name: "Delivery and Removal",
      description: "Authorize and control information system components entering and exiting the facility.",
      category: "physical-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "low",
      implementation_guidance: "Screen and inspect all incoming deliveries for unauthorized devices or modifications. Authorize and document all equipment entering and exiting the facility. Maintain logs of all deliveries and removals. Use designated receiving areas separate from system processing areas.",
      checks: [
        { id: "NIST-800-53-PE-16-C1", description: "Incoming deliveries screened and inspected", status: "not-implemented" },
        { id: "NIST-800-53-PE-16-C2", description: "Equipment entry/exit authorized and logged", status: "not-implemented" },
      ],
    },

    // ============================================================
    // PL — PLANNING
    // ============================================================

    {
      id: "NIST-800-53-PL-2",
      name: "System Security and Privacy Plans",
      description: "Develop and document a system security and privacy plan for the system.",
      category: "planning",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop a System Security Plan (SSP) that documents: system boundary, system environment, security controls implemented, and roles/responsibilities. Review and update the plan upon significant changes and at least annually. Protect the SSP from unauthorized disclosure. Designate a system owner responsible for the plan.",
      checks: [
        { id: "NIST-800-53-PL-2-C1", description: "System Security Plan documented", status: "not-implemented" },
        { id: "NIST-800-53-PL-2-C2", description: "Plan includes system boundary, environment, and controls", status: "not-implemented" },
        { id: "NIST-800-53-PL-2-C3", description: "Plan reviewed and updated at least annually", status: "not-implemented" },
        { id: "NIST-800-53-PL-2-C4", description: "Plan protected from unauthorized disclosure", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PL-8",
      name: "Security and Privacy Architectures",
      description: "Develop security and privacy architectures for the system.",
      category: "planning",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Develop security and privacy architectures that describe: architecture principles, security architecture, how controls are integrated, and alignment with enterprise architecture. Review and update architectures when significant changes occur. Reflect architectures in system design documentation.",
      checks: [
        { id: "NIST-800-53-PL-8-C1", description: "Security architecture documented", status: "not-implemented" },
        { id: "NIST-800-53-PL-8-C2", description: "Architecture reflects integration of security controls", status: "not-implemented" },
        { id: "NIST-800-53-PL-8-C3", description: "Architecture aligned with enterprise architecture", status: "not-implemented" },
      ],
    },

    // ============================================================
    // PS — PERSONNEL SECURITY
    // ============================================================

    {
      id: "NIST-800-53-PS-2",
      name: "Position Risk Designation",
      description: "Assign a risk designation to all positions within the organization.",
      category: "personnel-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Assign risk levels (low, moderate, high) to all positions based on duties, access level, and potential for harm. Define screening requirements for each risk level. Review and update position designations when duties change. Document position risk designations and maintain inventory.",
      checks: [
        { id: "NIST-800-53-PS-2-C1", description: "Position risk designations assigned to all positions", status: "not-implemented" },
        { id: "NIST-800-53-PS-2-C2", description: "Screening requirements defined per risk level", status: "not-implemented" },
        { id: "NIST-800-53-PS-2-C3", description: "Designations reviewed when duties change", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PS-3",
      name: "Personnel Screening",
      description: "Screen individuals prior to authorizing access to organizational information and systems.",
      category: "personnel-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Conduct background checks before granting access. Verify identity, education, employment history, and criminal records. Level of screening corresponds to position risk designation. Re-screen personnel when a triggering event occurs (e.g., security incident, change in clearance). Document screening results.",
      checks: [
        { id: "NIST-800-53-PS-3-C1", description: "Background checks conducted before access is granted", status: "not-implemented" },
        { id: "NIST-800-53-PS-3-C2", description: "Screening level matches position risk", status: "not-implemented" },
        { id: "NIST-800-53-PS-3-C3", description: "Re-screening triggered by events", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PS-4",
      name: "Personnel Termination",
      description: "Terminate access to systems and facilities when employment ends.",
      category: "personnel-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Disable access to logical systems within 2 hours of termination. Revoke facility access badges/credentials. Recover organizational property (laptops, mobile devices, keys). Notify security personnel of termination. Review access logs for terminated personnel activity.",
      checks: [
        { id: "NIST-800-53-PS-4-C1", description: "Logical access disabled within 2 hours of termination", status: "not-implemented" },
        { id: "NIST-800-53-PS-4-C2", description: "Facility access and badges revoked", status: "not-implemented" },
        { id: "NIST-800-53-PS-4-C3", description: "Organizational property recovered", status: "not-implemented" },
        { id: "NIST-800-53-PS-4-C4", description: "Termination access logs reviewed", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PS-5",
      name: "Personnel Transfer",
      description: "Review and modify logical and physical access authorizations when personnel are transferred.",
      category: "personnel-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Review and modify access authorizations when personnel are transferred to new positions. Revoke access no longer required for the new position. Initiate new screening requirements if the new position has a higher risk designation. Ensure transfers are documented and coordinated with HR, IT, and security.",
      checks: [
        { id: "NIST-800-53-PS-5-C1", description: "Access reviewed and modified upon transfer", status: "not-implemented" },
        { id: "NIST-800-53-PS-5-C2", description: "Unnecessary access revoked after transfer", status: "not-implemented" },
        { id: "NIST-800-53-PS-5-C3", description: "Transfers coordinated with HR, IT, and security", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PS-7",
      name: "Third-Party Personnel Security",
      description: "Ensure that third-party providers satisfy personnel security requirements.",
      category: "personnel-security",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Require third-party providers (contractors, service providers) to comply with personnel security requirements. Include screening requirements in contracts. Verify that third-party personnel have undergone appropriate screening. Require third parties to notify the organization within 24 hours of personnel termination or transfer.",
      checks: [
        { id: "NIST-800-53-PS-7-C1", description: "Third-party personnel security requirements in contracts", status: "not-implemented" },
        { id: "NIST-800-53-PS-7-C2", description: "Third-party screening verified", status: "not-implemented" },
        { id: "NIST-800-53-PS-7-C3", description: "Third-party notifies of termination/transfer within 24h", status: "not-implemented" },
      ],
    },

    // ============================================================
    // PT — PII PROCESSING AND TRANSPARENCY
    // ============================================================

    {
      id: "NIST-800-53-PT-1",
      name: "PII Processing",
      description: "Identify, document, and minimize the processing of PII.",
      category: "privacy",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Identify and document all processing activities involving PII. Minimize the collection, use, retention, and disclosure of PII to the minimum necessary. Conduct a Privacy Impact Assessment (PIA). Establish purpose specifications for each PII processing activity. Implement data minimization strategies.",
      checks: [
        { id: "NIST-800-53-PT-1-C1", description: "PII processing activities identified and documented", status: "not-implemented" },
        { id: "NIST-800-53-PT-1-C2", description: "PIA conducted for systems processing PII", status: "not-implemented" },
        { id: "NIST-800-53-PT-1-C3", description: "Data minimization implemented", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PT-2",
      name: "Consent and Notice",
      description: "Provide notice and obtain consent for the processing of PII where appropriate.",
      category: "privacy",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Provide clear and conspicuous notice of PII collection, use, sharing, and retention. Obtain affirmative consent for sensitive PII processing. Provide mechanisms for individuals to withdraw consent. Maintain records of consent. Ensure notices are available at the point of collection.",
      checks: [
        { id: "NIST-800-53-PT-2-C1", description: "Privacy notices provided at point of collection", status: "not-implemented" },
        { id: "NIST-800-53-PT-2-C2", description: "Affirmative consent obtained for sensitive PII", status: "not-implemented" },
        { id: "NIST-800-53-PT-2-C3", description: "Consent withdrawal mechanism available", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PT-3",
      name: "Redaction",
      description: "Redact PII from documents, reports, and records before release.",
      category: "privacy",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Implement redaction procedures for documents containing PII that are released to the public or external parties. Use automated redaction tools where possible. Define PII elements requiring redaction (SSN, passport numbers, financial accounts). Verify redaction effectiveness before release.",
      checks: [
        { id: "NIST-800-53-PT-3-C1", description: "Redaction procedures documented", status: "not-implemented" },
        { id: "NIST-800-53-PT-3-C2", description: "Automated redaction tools deployed", status: "not-implemented" },
        { id: "NIST-800-53-PT-3-C3", description: "Redaction verified before release", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PT-6",
      name: "PII Monitoring and Disclosure",
      description: "Monitor and audit access to and disclosure of PII.",
      category: "privacy",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Log and monitor all access to PII. Audit PII disclosures to ensure they are authorized and properly documented. Implement data loss prevention (DLP) to detect unauthorized PII transfers. Generate periodic reports on PII access patterns. Alert on anomalous access patterns.",
      checks: [
        { id: "NIST-800-53-PT-6-C1", description: "All PII access logged and monitored", status: "not-implemented" },
        { id: "NIST-800-53-PT-6-C2", description: "PII disclosures audited and documented", status: "not-implemented" },
        { id: "NIST-800-53-PT-6-C3", description: "DLP deployed for unauthorized PII transfer detection", status: "not-implemented" },
        { id: "NIST-800-53-PT-6-C4", description: "Anomalous access patterns trigger alerts", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-PT-7",
      name: "PII Destruction and Disposal",
      description: "Destroy or dispose of PII when it is no longer needed for the specified purpose.",
      category: "privacy",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Establish retention schedules defining how long PII is retained. Securely destroy or dispose of PII when no longer needed. Use NIST SP 800-88 compliant methods for media sanitization. Document destruction actions including date, method, and personnel. Verify destruction effectiveness.",
      checks: [
        { id: "NIST-800-53-PT-7-C1", description: "PII retention schedules established", status: "not-implemented" },
        { id: "NIST-800-53-PT-7-C2", description: "Secure destruction methods applied (SP 800-88)", status: "not-implemented" },
        { id: "NIST-800-53-PT-7-C3", description: "Destruction actions documented and verified", status: "not-implemented" },
      ],
    },

    // ============================================================
    // RA — RISK ASSESSMENT
    // ============================================================

    {
      id: "NIST-800-53-RA-3",
      name: "Risk Assessment",
      description: "Conduct a risk assessment of the system and environment of operation.",
      category: "risk-assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Conduct risk assessments using a defined methodology (NIST SP 800-30). Identify threats, vulnerabilities, likelihoods, and impacts. Assess risk to operations, assets, individuals, and other organizations. Document risk assessment results. Update risk assessments annually or upon significant changes.",
      checks: [
        { id: "NIST-800-53-RA-3-C1", description: "Risk assessment methodology documented (SP 800-30)", status: "not-implemented" },
        { id: "NIST-800-53-RA-3-C2", description: "Threats, vulnerabilities, and impacts identified", status: "not-implemented" },
        { id: "NIST-800-53-RA-3-C3", description: "Risk assessment results documented", status: "not-implemented" },
        { id: "NIST-800-53-RA-3-C4", description: "Assessment updated annually or after changes", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-RA-5",
      name: "Vulnerability Monitoring and Scanning",
      description: "Scan for vulnerabilities in the system and remediate in a timely manner.",
      category: "risk-assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Scan for vulnerabilities at least weekly using automated tools (e.g., Nessus, Qualys, OpenVAS). Scan after significant system changes. Remediate vulnerabilities based on severity: critical within 15 days, high within 30 days, medium within 90 days. Share vulnerability information with security teams. Monitor for new vulnerabilities using threat intelligence feeds.",
      checks: [
        { id: "NIST-800-53-RA-5-C1", description: "Automated vulnerability scanning at least weekly", status: "not-implemented" },
        { id: "NIST-800-53-RA-5-C2", description: "Scans conducted after significant changes", status: "not-implemented" },
        { id: "NIST-800-53-RA-5-C3", description: "Remediation SLAs: critical 15d, high 30d, medium 90d", status: "not-implemented" },
        { id: "NIST-800-53-RA-5-C4", description: "Vulnerability intel feeds monitored", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-RA-7",
      name: "Risk Response",
      description: "Respond to identified risks in accordance with the risk assessment results.",
      category: "risk-assessment",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Select and implement risk responses (accept, mitigate, transfer, avoid). Document risk response decisions including rationale and approval. Track remediation of identified risks. Report risk response status to authorizing officials. Reassess residual risk after mitigation.",
      checks: [
        { id: "NIST-800-53-RA-7-C1", description: "Risk responses selected and documented", status: "not-implemented" },
        { id: "NIST-800-53-RA-7-C2", description: "Risk response approvals recorded", status: "not-implemented" },
        { id: "NIST-800-53-RA-7-C3", description: "Remediation tracked and reported", status: "not-implemented" },
      ],
    },

    // ============================================================
    // SA — SYSTEM AND SERVICES ACQUISITION
    // ============================================================

    {
      id: "NIST-800-53-SA-3",
      name: "Supply Chain Protection",
      description: "Protect the supply chain for the system and system components.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Develop and implement a supply chain risk management (SCRM) plan. Identify and assess critical system components and their suppliers. Require suppliers to implement security controls. Verify the integrity of hardware and software received from suppliers (SBOM, code signing, hash verification). Monitor supply chain threats.",
      checks: [
        { id: "NIST-800-53-SA-3-C1", description: "SCRM plan developed and implemented", status: "not-implemented" },
        { id: "NIST-800-53-SA-3-C2", description: "Critical components and suppliers identified", status: "not-implemented" },
        { id: "NIST-800-53-SA-3-C3", description: "Supplier security requirements in contracts", status: "not-implemented" },
        { id: "NIST-800-53-SA-3-C4", description: "Component integrity verified (SBOM, signing)", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SA-4",
      name: "Acquisition Process",
      description: "Include security and privacy requirements in acquisition contracts and verify conformance.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Document security and privacy requirements for systems, components, and services. Include requirements in acquisition contracts and statements of work. Require vendors to demonstrate compliance through documentation, testing, or third-party assessments. Verify conformance throughout the lifecycle.",
      checks: [
        { id: "NIST-800-53-SA-4-C1", description: "Security requirements defined for acquisitions", status: "not-implemented" },
        { id: "NIST-800-53-SA-4-C2", description: "Requirements included in contracts/SOWs", status: "not-implemented" },
        { id: "NIST-800-53-SA-4-C3", description: "Vendor compliance verified through assessment", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SA-8",
      name: "Security Engineering Principles",
      description: "Apply security engineering principles in the specification, design, development, and implementation of the system.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Apply security engineering principles including: defense-in-depth, secure defaults, fail-safe defaults, least privilege, economy of mechanism, complete mediation, open design, separation of privilege, least common mechanism, and psychological acceptability. Implement threat modeling during design. Use secure design patterns and architecture.",
      checks: [
        { id: "NIST-800-53-SA-8-C1", description: "Security engineering principles applied in design", status: "not-implemented" },
        { id: "NIST-800-53-SA-8-C2", description: "Threat modeling conducted during design phase", status: "not-implemented" },
        { id: "NIST-800-53-SA-8-C3", description: "Secure design patterns and architecture used", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SA-9",
      name: "External System Services",
      description: "Require providers of external system services to implement security and privacy controls.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Require cloud providers and external service providers to implement required security controls. Define security requirements in service-level agreements (SLAs). Monitor provider security control implementation. Conduct periodic assessments of provider security. Define procedures for terminating service agreements.",
      checks: [
        { id: "NIST-800-53-SA-9-C1", description: "Security requirements defined for external services", status: "not-implemented" },
        { id: "NIST-800-53-SA-9-C2", description: "Requirements in SLAs", status: "not-implemented" },
        { id: "NIST-800-53-SA-9-C3", description: "Provider security assessed periodically", status: "not-implemented" },
        { id: "NIST-800-53-SA-9-C4", description: "Service termination procedures defined", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SA-11",
      name: "Developer Testing and Evaluation",
      description: "Require developers to create and implement a security assessment plan and perform testing.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Require developers to perform security testing including: static code analysis (SAST), dynamic application security testing (DAST), fuzzing, and penetration testing. Implement code review processes. Require vulnerability remediation before deployment. Verify security functionality through independent testing.",
      checks: [
        { id: "NIST-800-53-SA-11-C1", description: "SAST integrated into CI/CD pipeline", status: "not-implemented" },
        { id: "NIST-800-53-SA-11-C2", description: "DAST conducted on applications", status: "not-implemented" },
        { id: "NIST-800-53-SA-11-C3", description: "Penetration testing conducted annually", status: "not-implemented" },
        { id: "NIST-800-53-SA-11-C4", description: "Code review process implemented", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SA-22",
      name: "Unsupported System Components",
      description: "Replace system components when support for the components is no longer available from the vendor.",
      category: "acquisition",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Track vendor support status for all system components. Replace unsupported hardware, software, and firmware. When replacement is not immediately possible, implement compensating controls and document the risk. Maintain an inventory of unsupported components with upgrade/replacement plans.",
      checks: [
        { id: "NIST-800-53-SA-22-C1", description: "Vendor support status tracked for all components", status: "not-implemented" },
        { id: "NIST-800-53-SA-22-C2", description: "Unsupported components replaced or compensated", status: "not-implemented" },
        { id: "NIST-800-53-SA-22-C3", description: "Inventory of unsupported components maintained", status: "not-implemented" },
      ],
    },

    // ============================================================
    // SC — SYSTEM AND COMMUNICATIONS PROTECTION
    // ============================================================

    {
      id: "NIST-800-53-SC-5",
      name: "Denial of Service Protection",
      description: "Protect against or limit the effects of denial of service (DoS) attacks.",
      category: "system-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Deploy DDoS protection (e.g., Cloudflare, AWS Shield). Implement rate limiting and connection throttling. Configure auto-scaling to handle traffic spikes. Monitor for DoS attack patterns. Maintain a response plan for DoS incidents. Restrict internal resource consumption (CPU, memory, connections).",
      checks: [
        { id: "NIST-800-53-SC-5-C1", description: "DDoS protection deployed", status: "not-implemented" },
        { id: "NIST-800-53-SC-5-C2", description: "Rate limiting and connection throttling implemented", status: "not-implemented" },
        { id: "NIST-800-53-SC-5-C3", description: "DoS monitoring and response plan in place", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SC-8",
      name: "Transmission Confidentiality and Integrity",
      description: "Protect the confidentiality and integrity of transmitted information.",
      category: "system-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement TLS 1.2 or higher for all external data transmissions. Use mutual TLS (mTLS) for service-to-service communication. Enforce HSTS for web applications. Implement message-level encryption for sensitive data where needed. Verify cryptographic algorithm strength periodically.",
      checks: [
        { id: "NIST-800-53-SC-8-C1", description: "TLS 1.2+ enforced for all external communications", status: "not-implemented" },
        { id: "NIST-800-53-SC-8-C2", description: "HSTS enabled for web applications", status: "not-implemented" },
        { id: "NIST-800-53-SC-8-C3", description: "mTLS for internal service-to-service communication", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SC-12",
      name: "Cryptographic Key Establishment and Management",
      description: "Establish and manage cryptographic keys for cryptography used in the system.",
      category: "system-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Establish and manage cryptographic keys using NIST-approved algorithms and key lengths. Implement a key management system (KMS). Define key lifecycle procedures: generation, distribution, storage, rotation, and destruction. Use hardware security modules (HSMs) for critical keys. Maintain an inventory of cryptographic keys.",
      checks: [
        { id: "NIST-800-53-SC-12-C1", description: "Key management system deployed", status: "not-implemented" },
        { id: "NIST-800-53-SC-12-C2", description: "Key lifecycle procedures documented", status: "not-implemented" },
        { id: "NIST-800-53-SC-12-C3", description: "HSM used for critical key storage", status: "not-implemented" },
        { id: "NIST-800-53-SC-12-C4", description: "Key inventory maintained", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SC-13",
      name: "Cryptographic Protection",
      description: "Determine and document the cryptographic uses and implementations in the system.",
      category: "system-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use FIPS 140-2/140-3 validated cryptographic modules. Implement encryption at rest using AES-256-GCM. Use only NIST-approved algorithms. Disable deprecated algorithms and protocols (RC4, DES, SSL, TLS 1.0/1.1). Document all cryptographic uses including: data at rest, data in transit, hashing, digital signatures.",
      checks: [
        { id: "NIST-800-53-SC-13-C1", description: "FIPS 140-2/3 validated crypto modules used", status: "not-implemented" },
        { id: "NIST-800-53-SC-13-C2", description: "Deprecated algorithms disabled (RC4, DES, SSL, TLS 1.0/1.1)", status: "not-implemented" },
        { id: "NIST-800-53-SC-13-C3", description: "Cryptographic uses documented", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SC-28",
      name: "Protection of Information at Rest",
      description: "Protect the confidentiality and integrity of information at rest.",
      category: "system-protection",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement full-disk encryption on all servers, laptops, and mobile devices. Encrypt database contents at rest using AES-256. Implement file-level or field-level encryption for sensitive data. Use encrypted storage volumes (EBS encryption, Azure Disk Encryption, GCP Persistent Disk encryption). Regularly verify encryption status.",
      checks: [
        { id: "NIST-800-53-SC-28-C1", description: "Full-disk encryption on all endpoints", status: "not-implemented" },
        { id: "NIST-800-53-SC-28-C2", description: "Database encryption at rest (AES-256)", status: "not-implemented" },
        { id: "NIST-800-53-SC-28-C3", description: "Field-level encryption for sensitive data", status: "not-implemented" },
        { id: "NIST-800-53-SC-28-C4", description: "Encrypted storage volumes verified", status: "not-implemented" },
      ],
    },

    // ============================================================
    // SI — SYSTEM AND INFORMATION INTEGRITY
    // ============================================================

    {
      id: "NIST-800-53-SI-2",
      name: "Flaw Remediation",
      description: "Identify, report, and correct system flaws and vulnerabilities.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Identify and remediate flaws including: security vulnerabilities, bugs, and configuration errors. Install security-relevant software and firmware updates within defined timeframes: critical 48 hours, high 7 days, medium 30 days, low 90 days. Test updates before deployment. Remove flawed components from operational systems.",
      checks: [
        { id: "NIST-800-53-SI-2-C1", description: "Flaw identification and reporting process documented", status: "not-implemented" },
        { id: "NIST-800-53-SI-2-C2", description: "Patch SLAs enforced: critical 48h, high 7d, medium 30d", status: "not-implemented" },
        { id: "NIST-800-53-SI-2-C3", description: "Updates tested before deployment", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SI-3",
      name: "Malicious Code Protection",
      description: "Implement protection against malicious code at system entry and exit points.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Deploy endpoint detection and response (EDR) or anti-malware solutions on all endpoints and servers. Enable real-time scanning for malicious code at system entry/exit points (email gateways, web proxies, file servers). Automatically update malicious code detection signatures. Scan files from external sources before use. Block execution of unauthorized software.",
      checks: [
        { id: "NIST-800-53-SI-3-C1", description: "EDR/anti-malware deployed on all endpoints and servers", status: "not-implemented" },
        { id: "NIST-800-53-SI-3-C2", description: "Real-time scanning at entry/exit points", status: "not-implemented" },
        { id: "NIST-800-53-SI-3-C3", description: "Signatures auto-updated", status: "not-implemented" },
        { id: "NIST-800-53-SI-3-C4", description: "Unauthorized software execution blocked", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SI-4",
      name: "System Monitoring",
      description: "Monitor the system and inbound/outbound communications for security and privacy anomalies.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Deploy a SIEM (Security Information and Event Management) solution. Monitor network traffic for anomalies, intrusions, and unauthorized connections. Deploy intrusion detection/prevention systems (IDS/IPS). Monitor system behavior for indicators of compromise (IoCs). Integrate threat intelligence feeds. Define alerting thresholds and escalation procedures.",
      checks: [
        { id: "NIST-800-53-SI-4-C1", description: "SIEM deployed and centralized logging active", status: "not-implemented" },
        { id: "NIST-800-53-SI-4-C2", description: "IDS/IPS deployed on network perimeter", status: "not-implemented" },
        { id: "NIST-800-53-SI-4-C3", description: "Threat intelligence integrated", status: "not-implemented" },
        { id: "NIST-800-53-SI-4-C4", description: "Alerting thresholds and escalation defined", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SI-7",
      name: "Software, Firmware, and Information Integrity",
      description: "Detect unauthorized changes to software, firmware, and information.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement file integrity monitoring (FIM) for critical system files, configuration files, and software. Perform integrity checks upon system startup and periodically. Verify code signing certificates for software updates. Alert on unauthorized changes. Use digital signatures for software distribution.",
      checks: [
        { id: "NIST-800-53-SI-7-C1", description: "File integrity monitoring (FIM) deployed", status: "not-implemented" },
        { id: "NIST-800-53-SI-7-C2", description: "Integrity checks on startup and periodically", status: "not-implemented" },
        { id: "NIST-800-53-SI-7-C3", description: "Code signing verified for software updates", status: "not-implemented" },
        { id: "NIST-800-53-SI-7-C4", description: "Unauthorized changes trigger alerts", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SI-10",
      name: "Information Input Validation",
      description: "Check the validity of information inputs to the system.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement input validation for all user-supplied data. Use parameterized queries to prevent SQL injection. Sanitize inputs to prevent XSS. Validate data format, type, length, and range. Implement server-side validation (never rely on client-side only). Use allow-lists for acceptable input values. Reject and log invalid inputs.",
      checks: [
        { id: "NIST-800-53-SI-10-C1", description: "Server-side input validation for all endpoints", status: "not-implemented" },
        { id: "NIST-800-53-SI-10-C2", description: "Parameterized queries prevent SQL injection", status: "not-implemented" },
        { id: "NIST-800-53-SI-10-C3", description: "XSS prevention via output encoding/sanitization", status: "not-implemented" },
        { id: "NIST-800-53-SI-10-C4", description: "Allow-lists used for acceptable input values", status: "not-implemented" },
      ],
    },
    {
      id: "NIST-800-53-SI-12",
      name: "Information Handling and Retention",
      description: "Handle and retain information in accordance with applicable requirements.",
      category: "system-integrity",
      framework: "NIST-800-53",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Establish information handling procedures based on data classification levels. Define retention periods for each data category. Implement automated retention enforcement (e.g., auto-delete after retention period). Securely dispose of information that has exceeded its retention period. Document data handling and retention procedures.",
      checks: [
        { id: "NIST-800-53-SI-12-C1", description: "Data handling procedures by classification level", status: "not-implemented" },
        { id: "NIST-800-53-SI-12-C2", description: "Retention periods defined per data category", status: "not-implemented" },
        { id: "NIST-800-53-SI-12-C3", description: "Automated retention enforcement implemented", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "nist-800-53",
    name: "NIST SP 800-53 Rev 5 Policy Pack (Government-Grade)",
    description: "Full NIST SP 800-53 Rev 5 security and privacy controls across all 18 control families: AC, AT, AU, CA, CM, CP, IA, IR, MA, MP, PE, PL, PM, PS, PT, RA, SA, SC, SI. **Designed for government systems, federal agencies, federal contractors, and FedRAMP compliance.** This is the official government compliance baseline used by all US federal information systems.",
    version: "5.0.0",
    project_types: [
      "government-system",
      "saas",
      "healthcare-system",
      "generic-web-application",
      "api-backend",
      "mobile-application",
    ],
    controls,
    frameworks: ["NIST-800-53"],
  };
}
