import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createOWASPLLMPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "LLM-001",
      name: "Prompt Injection Protection",
      description: "Protect against prompt injection attacks where malicious inputs manipulate the model into bypassing safety rules or revealing system prompts.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Separate system prompts from user inputs using structured delimiters. Implement input sanitization and length limits. Use a secondary model to classify inputs for injection attempts. Never expose raw system prompts in outputs. Log and alert on suspicious patterns.",
      checks: [
        { id: "LLM-001-C1", description: "System prompts isolated from user input", status: "not-implemented" },
        { id: "LLM-001-C2", description: "Input sanitization and injection detection", status: "not-implemented" },
        { id: "LLM-001-C3", description: "Suspicious pattern logging and alerting", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-002",
      name: "Insecure Output Handling and Validation",
      description: "Validate and sanitize LLM outputs before passing to downstream systems, rendering to users, or executing as code.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Treat all LLM output as untrusted. Validate output against expected schema before use. Encode output for the target context (HTML, SQL, shell). Never pass raw LLM output to eval(), exec(), or database queries. Implement output rate limiting.",
      checks: [
        { id: "LLM-002-C1", description: "Output schema validation before downstream use", status: "not-implemented" },
        { id: "LLM-002-C2", description: "Context-appropriate encoding of outputs", status: "not-implemented" },
        { id: "LLM-002-C2b", description: "No raw LLM output passed to execution functions", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-003",
      name: "Training Data Poisoning Prevention",
      description: "Prevent adversaries from manipulating training or fine-tuning data to introduce vulnerabilities, backdoors, or biases.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Validate and curate all training data sources. Implement data provenance tracking. Use statistical anomaly detection on training datasets. Restrict write access to training data pipelines. Test models for backdoor triggers after training.",
      checks: [
        { id: "LLM-003-C1", description: "Training data source validation", status: "not-implemented" },
        { id: "LLM-003-C2", description: "Data provenance tracking implemented", status: "not-implemented" },
        { id: "LLM-003-C3", description: "Post-training backdoor testing", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-004",
      name: "Model DoS Protection (Rate Limiting)",
      description: "Protect against denial-of-service attacks that exhaust model compute resources through expensive prompts or high-volume requests.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement per-user and per-IP rate limiting. Enforce maximum token limits per request. Set timeouts on model inference. Monitor for prompt stuffing (extremely long inputs). Use a queue with bounded concurrency. Implement cost-based limits.",
      checks: [
        { id: "LLM-004-C1", description: "Per-user rate limiting on AI endpoints", status: "not-implemented" },
        { id: "LLM-004-C2", description: "Maximum token limit per request", status: "not-implemented" },
        { id: "LLM-004-C3", description: "Inference timeout configured", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-005",
      name: "Supply Chain Validation for Models",
 description: "Validate the provenance and integrity of pre-trained models, embeddings, and plugins before integration.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Only download models from trusted sources (HuggingFace verified, official repos). Verify model checksums/signatures. Scan model files for embedded malware. Document model licenses and usage restrictions. Maintain an inventory of all model dependencies.",
      checks: [
        { id: "LLM-005-C1", description: "Model source verification (checksum/signature)", status: "not-implemented" },
        { id: "LLM-005-C2", description: "Model file malware scanning", status: "not-implemented" },
        { id: "LLM-005-C3", description: "Model dependency inventory maintained", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-006",
      name: "Sensitive Data Disclosure Prevention",
      description: "Prevent the LLM from disclosing sensitive training data, PII, API keys, or internal system information in its outputs.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Differential privacy techniques during training. PII detection and redaction on both inputs and outputs. Avoid including secrets or PII in training/fine-tuning data. Implement output filtering for sensitive patterns. Log all outputs for audit.",
      checks: [
        { id: "LLM-006-C1", description: "PII detection and redaction on outputs", status: "not-implemented" },
        { id: "LLM-006-C2", description: "No secrets/PII in training data", status: "not-implemented" },
        { id: "LLM-006-C3", description: "Output logging for audit purposes", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-007",
      name: "Insecure Plugin Design",
      description: "Plugins and tools connected to the LLM must validate inputs, enforce authorization, and limit blast radius.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Validate all plugin inputs independently of the LLM. Implement strict authorization per plugin action. Limit plugin data access to minimum required. Sandbox plugin execution. Rate-limit plugin calls. Log all plugin invocations.",
      checks: [
        { id: "LLM-007-C1", description: "Plugin input validation independent of LLM", status: "not-implemented" },
        { id: "LLM-007-C2", description: "Per-action authorization enforced", status: "not-implemented" },
        { id: "LLM-007-C3", description: "Plugin calls logged for audit", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-008",
      name: "Excessive Agency / Unbounded Actions",
      description: "Limit the actions an LLM agent can take autonomously. Prevent agents from performing destructive operations without human approval.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement human-in-the-loop for destructive actions (delete, write, send, execute). Define explicit allowlists of permitted actions. Set maximum scope per agent session. Implement rollback/undo for reversible actions. Log all autonomous decisions.",
      checks: [
        { id: "LLM-008-C1", description: "Human approval required for destructive actions", status: "not-implemented" },
        { id: "LLM-008-C2", description: "Explicit action allowlist defined", status: "not-implemented" },
        { id: "LLM-008-C3", description: "Autonomous decisions logged", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-009",
      name: "Overreliance and Output Grounding",
      description: "Prevent overreliance on LLM outputs by grounding responses, providing citations, and communicating uncertainty.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Implement RAG (Retrieval-Augmented Generation) to ground responses in verified data. Require source citations for factual claims. Display confidence scores where available. Add disclaimers about AI-generated content. Provide feedback mechanism for incorrect outputs.",
      checks: [
        { id: "LLM-009-C1", description: "RAG implementation for grounding", status: "not-implemented" },
        { id: "LLM-009-C2", description: "Source citations required for factual claims", status: "not-implemented" },
        { id: "LLM-009-C3", description: "AI-generated content disclaimers", status: "not-implemented" },
      ],
    },
    {
      id: "LLM-010",
      name: "Model Theft Protection",
      description: "Protect proprietary models from extraction attacks that attempt to clone the model through repeated queries.",
      category: "ai-security",
      framework: "OWASP-LLM",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement query rate limiting and volume monitoring. Detect extraction patterns (high-volume systematic queries). Watermark model outputs. Use API gateways with DDoS protection. Legal protections (NDAs, terms of service) for model access.",
      checks: [
        { id: "LLM-010-C1", description: "Query volume monitoring and anomaly detection", status: "not-implemented" },
        { id: "LLM-010-C2", description: "Output watermarking implemented", status: "not-implemented" },
        { id: "LLM-010-C3", description: "API gateway with DDoS protection", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "owasp-llm",
    name: "OWASP LLM Top 10 Policy Pack",
    description: "OWASP Top 10 for Large Language Model Applications — covers prompt injection, insecure output handling, training data poisoning, model DoS, supply chain, data disclosure, plugin security, excessive agency, overreliance, and model theft.",
    version: "1.0.0",
    project_types: ["ai-application", "mcp-server"],
    controls,
    frameworks: ["OWASP-LLM"],
  };
}
