import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createOWASPMASVSPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "MASVS-001",
      name: "Secure Local Storage of Sensitive Data",
      description: "Sensitive data (passwords, tokens, PII) must be stored securely using platform keychain/keystore, not in plaintext files or SharedPreferences.",
      category: "data-protection",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Use iOS Keychain (SecItemAdd) or Android Keystore (AndroidKeyStore provider) for credentials and tokens. Never store secrets in SharedPreferences, UserDefaults, SQLite, or plain files. Use platform biometric-protected storage for highest sensitivity data.",
      checks: [
        { id: "MASVS-001-C1", description: "Keychain/Keystore used for credential storage", status: "not-implemented" },
        { id: "MASVS-001-C2", description: "No secrets in SharedPreferences/UserDefaults/SQLite", status: "not-implemented" },
        { id: "MASVS-001-C3", description: "Biometric protection enabled for highest-sensitivity data", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-002",
      name: "No Keystroke Logging or Screen Capture",
      description: "The app must prevent keystroke logging, screen capture, and screen recording of sensitive screens.",
      category: "data-protection",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "On Android, set `FLAG_SECURE` on sensitive activities. On iOS, use `UITextField.isSecureTextEntry` for password fields and overlay protected views. Detect and warn about screen recording. Disable autocorrect and custom keyboards on sensitive inputs.",
      checks: [
        { id: "MASVS-002-C1", description: "FLAG_SECURE set on sensitive Android activities", status: "not-implemented" },
        { id: "MASVS-002-C2", description: "Screen capture detection on iOS", status: "not-implemented" },
        { id: "MASVS-002-C3", description: "Custom keyboards disabled on sensitive inputs", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-003",
      name: "Secure Key Management (No Hardcoded Keys)",
      description: "Cryptographic keys, API keys, and secrets must not be hardcoded in the app binary. Use runtime key exchange or secure enclave.",
      category: "cryptography",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Never hardcode keys in source code, resources, or assets. Use certificate pinning to secure key exchange. Store keys in platform secure enclave (Keychain/Keystore). Consider server-side key management with mutual TLS for highest security.",
      checks: [
        { id: "MASVS-003-C1", description: "No hardcoded API keys or secrets in source", status: "not-implemented" },
        { id: "MASVS-003-C2", description: "Keys stored in secure enclave", status: "not-implemented" },
        { id: "MASVS-003-C3", description: "Key rotation mechanism implemented", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-004",
      name: "Strong Authentication with Biometrics",
      description: "The app must support biometric authentication (Face ID/Touch ID/Fingerprint) with device passcode as fallback.",
      category: "authentication",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use LocalAuthentication (iOS) or BiometricPrompt (Android) for biometric auth. Always provide passcode fallback. Use biometric-protected Keychain/Keystore for the auth token. Never store biometric data — rely on platform APIs.",
      checks: [
        { id: "MASVS-004-C1", description: "Biometric authentication implemented", status: "not-implemented" },
        { id: "MASVS-004-C2", description: "Passcode fallback available", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-005",
      name: "Certificate Pinning for Network Communication",
      description: "All network communication must use certificate pinning to prevent MITM attacks.",
      category: "network-security",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Pin server certificates or public keys in the app. Use TrustKit (iOS) or Network Security Config with pin-set (Android). Include backup pins for key rotation. Enforce TLS 1.2+ minimum. Handle pin validation failures by aborting the connection.",
      checks: [
        { id: "MASVS-005-C1", description: "Certificate pinning configured", status: "not-implemented" },
        { id: "MASVS-005-C2", description: "Backup pin included for rotation", status: "not-implemented" },
        { id: "MASVS-005-C3", description: "TLS 1.2+ enforced", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-006",
      name: "Code Obfuscation and Anti-Tampering",
      description: "The app binary should be obfuscated and include integrity checks to deter reverse engineering and tampering.",
      category: "resilience",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Use ProGuard/R8 (Android) for code obfuscation. Implement runtime integrity checks (SafetyNet/Play Integrity API on Android, DeviceCheck on iOS). Detect debugger attachment. Use anti-frida/anti-hooking techniques for high-security apps.",
      checks: [
        { id: "MASVS-006-C1", description: "Code obfuscation enabled (ProGuard/R8)", status: "not-implemented" },
        { id: "MASVS-006-C2", description: "Runtime integrity checks implemented", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-007",
      name: "Input Validation on All Inputs",
      description: "All user inputs, deep links, IPC inputs, and web view inputs must be validated and sanitized.",
      category: "validation",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Validate all inputs on both client and server. Use allowlists for acceptable values. Sanitize inputs before passing to SQL, file, or command contexts. Validate deep link parameters. Restrict WebView JavaScript interfaces.",
      checks: [
        { id: "MASVS-007-C1", description: "All user inputs validated", status: "not-implemented" },
        { id: "MASVS-007-C2", description: "Deep link parameters validated", status: "not-implemented" },
        { id: "MASVS-007-C3", description: "WebView inputs sanitized", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-008",
      name: "Secure IPC Between App Components",
      description: "Inter-process communication between app components (Activities, Services, Content Providers, Broadcast Receivers) must be secured.",
      category: "platform-security",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Set `android:exported=\"false\"` on components not needed by other apps. Use explicit intents over implicit. Apply signature-level permissions for internal communication. Validate all IPC inputs. Use App Sandbox and App Groups correctly on iOS.",
      checks: [
        { id: "MASVS-008-C1", description: "Exported components minimized and secured", status: "not-implemented" },
        { id: "MASVS-008-C2", description: "Explicit intents used for internal IPC", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-009",
      name: "Tapjacking and Clickjacking Protection",
      description: "The app must protect against tapjacking attacks where overlay windows trick users into tapping hidden elements.",
      category: "platform-security",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "low",
      implementation_guidance: "Set `android:filterTouchesWhenObscured=\"true\"` on sensitive views. Detect and block overlay windows. Use `setFilterTouchesWhenObscured(true)` programmatically for critical UI elements.",
      checks: [
        { id: "MASVS-009-C1", description: "filterTouchesWhenObscured set on sensitive views", status: "not-implemented" },
        { id: "MASVS-009-C2", description: "Overlay window detection implemented", status: "not-implemented" },
      ],
    },
    {
      id: "MASVS-010",
      name: "Runtime Integrity Checks (Root/Jailbreak Detection)",
      description: "The app must detect rooted (Android) or jailbroken (iOS) devices and respond appropriately.",
      category: "resilience",
      framework: "OWASP-MASVS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use RootBeer (Android) or jailbreak detection libraries (iOS). Check for common root indicators (su binary, Magisk, Cydia). On detected compromise, either warn the user, disable sensitive features, or refuse to run. Never rely solely on client-side detection.",
      checks: [
        { id: "MASVS-010-C1", description: "Root/jailbreak detection implemented", status: "not-implemented" },
        { id: "MASVS-010-C2", description: "Appropriate response on compromised device", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "owasp-masvs",
    name: "OWASP MASVS (Mobile Application Security Verification Standard) Policy Pack",
    description: "OWASP MASVS controls for mobile application security covering storage, crypto, network, authentication, and resilience.",
    version: "1.0.0",
    project_types: ["mobile-application"],
    controls,
    frameworks: ["OWASP-MASVS"],
  };
}
