import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createPCIDSSPolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "PCI-001",
      name: "Network Segmentation for Cardholder Data",
      description: "Cardholder Data Environment (CDE) must be isolated from other networks via firewalls, VLANs, or network segmentation.",
      category: "network-security",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Isolate the CDE in its own VLAN/subnet. Implement firewalls between CDE and corporate networks. Deny all traffic by default, allow only necessary ports. Document segmentation in a network diagram. Test segmentation quarterly.",
      checks: [
        { id: "PCI-001-C1", description: "CDE isolated via firewall/VLAN", status: "not-implemented" },
        { id: "PCI-001-C2", description: "Default-deny rules between zones", status: "not-implemented" },
        { id: "PCI-001-C3", description: "Quarterly segmentation testing", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-002",
      name: "Encryption of Cardholder Data in Transit",
      description: "Cardholder data must be encrypted during transmission using strong cryptography (TLS 1.2+).",
      category: "encryption",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Enforce TLS 1.2 minimum on all endpoints handling CHD. Disable SSL, TLS 1.0, 1.1. Use strong cipher suites (no RC4, no 3DES). Implement HSTS. Verify certificates with mutual TLS where applicable. Never transmit CHD over unencrypted channels (email, HTTP, FTP).",
      checks: [
        { id: "PCI-002-C1", description: "TLS 1.2+ enforced on all CHD endpoints", status: "not-implemented" },
        { id: "PCI-002-C2", description: "Weak protocols and ciphers disabled", status: "not-implemented" },
        { id: "PCI-002-C3", description: "HSTS header configured", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-003",
      name: "Encryption of Stored Cardholder Data",
      description: "Stored cardholder data (PAN) must be encrypted using strong, industry-accepted algorithms. Display PAN masked (max first 6/last 4 digits).",
      category: "encryption",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Encrypt stored PAN with AES-256 or equivalent. Use transparent data encryption (TDE) at database level. Implement field-level encryption for maximum security. Tokenize PAN where possible. Mask PAN in all displays (show only first 6 and last 4 digits). Do not store CVV/CVC after authorization.",
      checks: [
        { id: "PCI-003-C1", description: "PAN encrypted at rest (AES-256)", status: "not-implemented" },
        { id: "PCI-003-C2", description: "PAN masked in UI and logs (first 6/last 4)", status: "not-implemented" },
        { id: "PCI-003-C3", description: "CVV/CVC not stored post-authorization", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-004",
      name: "Access Control to Cardholder Data",
      description: "Access to cardholder data must be restricted on a need-to-know basis via role-based access control.",
      category: "access-control",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement RBAC with explicit roles for CDE access. Define need-to-know criteria per role. Default deny all access. Review access lists quarterly. Revoke access immediately upon role change or termination. Log all access to cardholder data.",
      checks: [
        { id: "PCI-004-C1", description: "RBAC with need-to-know enforcement", status: "not-implemented" },
        { id: "PCI-004-C2", description: "Quarterly access review", status: "not-implemented" },
        { id: "PCI-004-C3", description: "Access logging for CHD", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-005",
      name: "Unique ID for Each Person with Computer Access",
      description: "Every user with access to cardholder data must have a unique identification ID. No shared or generic accounts.",
      category: "authentication",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Assign unique user IDs to all personnel. Eliminate shared/generic accounts. Implement password complexity requirements (min 12 chars, mixed case, numbers, symbols). Enforce 90-day password rotation or use passphrases. Lock accounts after 6 failed attempts.",
      checks: [
        { id: "PCI-005-C1", description: "Unique user IDs (no shared accounts)", status: "not-implemented" },
        { id: "PCI-005-C2", description: "Password complexity requirements enforced", status: "not-implemented" },
        { id: "PCI-005-C3", description: "Account lockout after failed attempts", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-006",
      name: "MFA for All Access to Cardholder Data",
      description: "Multi-factor authentication is required for all access to the cardholder data environment, including remote and administrative access.",
      category: "authentication",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Require MFA for: all remote network access, all access to CDE, all administrative access. Use TOTP, hardware tokens, or push notifications (not SMS). Enforce MFA on VPN, SSH, RDP, web admin panels. Test MFA regularly.",
      checks: [
        { id: "PCI-006-C1", description: "MFA for all CDE access", status: "not-implemented" },
        { id: "PCI-006-C2", description: "MFA for remote and admin access", status: "not-implemented" },
        { id: "PCI-006-C3", description: "Non-SMS MFA methods used", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-007",
      name: "Audit Logging for All Access to CHD",
      description: "Audit logs must capture all access to cardholder data, including administrator actions, with sufficient detail for forensic analysis.",
      category: "audit-logging",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Log all access to CHD (read/write/delete). Include user ID, timestamp, action, resource, source IP. Log all admin actions (config changes, account creation). Forward logs to centralized, tamper-evident storage. Retain logs for at least 1 year (3 months online). Review daily.",
      checks: [
        { id: "PCI-007-C1", description: "All CHD access logged with required fields", status: "not-implemented" },
        { id: "PCI-007-C2", description: "Logs forwarded to centralized tamper-evident store", status: "not-implemented" },
        { id: "PCI-007-C3", description: "1-year retention with daily review", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-008",
      name: "Quarterly Vulnerability Scans",
      description: "Perform quarterly internal and external vulnerability scans by an ASV (Approved Scanning Vendor) for external-facing systems.",
      category: "vulnerability-management",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Run internal vulnerability scans quarterly (Nessus, Qualys). Use PCI ASV for quarterly external scans. Remediate all critical/high findings within 30 days. Rescan after remediation. Document scan results and remediation evidence.",
      checks: [
        { id: "PCI-008-C1", description: "Quarterly internal vulnerability scans", status: "not-implemented" },
        { id: "PCI-008-C2", description: "ASV external scans quarterly", status: "not-implemented" },
        { id: "PCI-008-C3", description: "Critical/high remediated within 30 days", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-009",
      name: "Annual Penetration Testing",
      description: "Perform annual penetration testing on the CDE and after any significant network or application change.",
      category: "vulnerability-management",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Engage qualified penetration testers annually. Cover both network-layer and application-layer testing. Include segmentation testing. Remediate findings per severity SLA. Retest after remediation. Document full report with evidence.",
      checks: [
        { id: "PCI-009-C1", description: "Annual penetration test performed", status: "not-implemented" },
        { id: "PCI-009-C2", description: "Segmentation testing included", status: "not-implemented" },
        { id: "PCI-009-C3", description: "Findings remediated and retested", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-010",
      name: "File Integrity Monitoring (FIM)",
      description: "Deploy file integrity monitoring to detect unauthorized changes to critical system files, configuration files, and content files.",
      category: "monitoring",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Deploy FIM tools (OSSEC, Tripwire, AIDE) on all systems in the CDE. Monitor critical OS files, application binaries, configuration files, and content files. Generate alerts on changes. Review FIM alerts daily. Establish baseline and whitelist known-good changes.",
      checks: [
        { id: "PCI-010-C1", description: "FIM deployed on all CDE systems", status: "not-implemented" },
        { id: "PCI-010-C2", description: "Critical files monitored with alerting", status: "not-implemented" },
        { id: "PCI-010-C3", description: "Daily FIM alert review", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-011",
      name: "Secure Software Development Practices",
      description: "Develop applications based on secure coding guidelines. Review custom code for vulnerabilities before release.",
      category: "secure-development",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Follow secure coding guidelines (OWASP ASVS). Implement code review (peer review + automated SAST). Train developers on secure coding. Separate dev/test/production environments. Remove test data and accounts before production. Implement change control procedures.",
      checks: [
        { id: "PCI-011-C1", description: "Secure coding guidelines followed", status: "not-implemented" },
        { id: "PCI-011-C2", description: "Code review (peer + SAST) before release", status: "not-implemented" },
        { id: "PCI-011-C3", description: "Separation of dev/test/prod environments", status: "not-implemented" },
      ],
    },
    {
      id: "PCI-012",
      name: "Change Control Procedures",
      description: "All changes to systems in the CDE must follow documented change control procedures with approval and rollback plans.",
      category: "change-management",
      framework: "PCI-DSS",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Document change request, impact analysis, approval, and testing. Require management approval for all production changes. Include rollback plan. Log all changes. Review changes post-implementation. No unauthorized or emergency changes without documented justification.",
      checks: [
        { id: "PCI-012-C1", description: "Documented change control process", status: "not-implemented" },
        { id: "PCI-012-C2", description: "Management approval for production changes", status: "not-implemented" },
        { id: "PCI-012-C3", description: "Rollback plans documented", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "pci-dss",
    name: "PCI DSS Policy Pack",
    description: "Payment Card Industry Data Security Standard (PCI DSS) controls for protecting cardholder data.",
    version: "1.0.0",
    project_types: ["saas", "api-backend", "generic-web-application"],
    controls,
    frameworks: ["PCI-DSS"],
  };
}
