import type { PolicyPack, Control } from "@greenarmor/ges-core";

export function createSOC2PolicyPack(): PolicyPack {
  const controls: Control[] = [
    {
      id: "SOC2-001",
      name: "Security — Logical and Physical Access Controls",
      description: "Implement logical access security software, infrastructure, and controls over IT assets to prevent unauthorized access.",
      category: "access-control",
      framework: "SOC2",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement RBAC with least-privilege principles. Use MFA for all access. Maintain current inventory of IT assets. Enforce password complexity and rotation. Regularly review access rights. Physical access controls (badge access, visitor logs) for data centers.",
      checks: [
        { id: "SOC2-001-C1", description: "RBAC with least-privilege implemented", status: "not-implemented" },
        { id: "SOC2-001-C2", description: "IT asset inventory maintained", status: "not-implemented" },
        { id: "SOC2-001-C3", description: "Quarterly access rights review", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-002",
      name: "Security — User Authentication and Identification",
      description: "Authenticate and authorize users before granting access to systems and data. Unique user IDs for all users.",
      category: "authentication",
      framework: "SOC2",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Unique user IDs for all personnel. MFA for remote and admin access. Password policy (12+ chars, complexity). Session timeout and lockout policies. Account provisioning/deproving workflow with HR integration. SSO where possible.",
      checks: [
        { id: "SOC2-002-C1", description: "Unique user IDs enforced", status: "not-implemented" },
        { id: "SOC2-002-C2", description: "MFA for remote and admin access", status: "not-implemented" },
        { id: "SOC2-002-C3", description: "Session timeout configured", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-003",
      name: "Security — Network Protection (Firewall, IDS/IPS)",
      description: "Implement perimeter security controls including firewalls, intrusion detection/prevention, and network segmentation.",
      category: "network-security",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Deploy next-gen firewalls with default-deny rules. Implement intrusion detection/prevention (IDS/IPS). Segment networks (DMZ, internal, CDE). Regular firewall rule reviews. DDoS protection. VPN for remote access. WAF for web applications.",
      checks: [
        { id: "SOC2-003-C1", description: "Firewall with default-deny rules", status: "not-implemented" },
        { id: "SOC2-003-C2", description: "IDS/IPS deployed", status: "not-implemented" },
        { id: "SOC2-003-C3", description: "Network segmentation implemented", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-004",
      name: "Availability — Backup and Recovery Procedures",
      description: "Establish backup and recovery procedures and test them periodically to ensure availability commitments are met.",
      category: "availability",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Define RPO and RTO objectives. Automate daily backups with encryption. Store backups off-site and in different availability zones. Test restoration quarterly. Document recovery procedures. Monitor backup completion and alert on failures.",
      checks: [
        { id: "SOC2-004-C1", description: "RPO/RTO defined and documented", status: "not-implemented" },
        { id: "SOC2-004-C2", description: "Encrypted automated backups", status: "not-implemented" },
        { id: "SOC2-004-C3", description: "Quarterly restore testing", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-005",
      name: "Availability — Environmental Protections",
      description: "Implement environmental protections at data centers including redundant power, cooling, and fire suppression.",
      category: "availability",
      framework: "SOC2",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "For on-prem: UPS/generators, HVAC, fire suppression, water detection. For cloud: select multi-AZ/multi-region deployment. Document vendor SLAs for infrastructure. Monitor environmental sensors. Annual DR exercise.",
      checks: [
        { id: "SOC2-005-C1", description: "Redundant power and cooling", status: "not-implemented" },
        { id: "SOC2-005-C2", description: "Multi-AZ or multi-region deployment", status: "not-implemented" },
        { id: "SOC2-005-C3", description: "Environmental monitoring", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-006",
      name: "Processing Integrity — Data Validation",
      description: "Implement controls to ensure data is processed completely, accurately, and on time. Validate inputs and outputs.",
      category: "processing-integrity",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Validate all data inputs (schema, range, type). Implement reconciliation controls for data processing. Monitor processing errors and alert. Log all data transformations. Implement error handling and retry mechanisms. Periodic data quality audits.",
      checks: [
        { id: "SOC2-006-C1", description: "Input validation on all data entry points", status: "not-implemented" },
        { id: "SOC2-006-C2", description: "Data reconciliation controls", status: "not-implemented" },
        { id: "SOC2-006-C3", description: "Processing error monitoring and alerting", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-007",
      name: "Confidentiality — Encryption and Data Segregation",
      description: "Encrypt confidential data at rest and in transit. Segregate confidential data from other data stores.",
      category: "confidentiality",
      framework: "SOC2",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Encrypt at rest with AES-256 (database TDE, disk encryption, S3 SSE). Encrypt in transit with TLS 1.2+. Implement data classification and label confidential data. Segregate confidential data stores. Use field-level encryption for highest sensitivity. Rotate encryption keys.",
      checks: [
        { id: "SOC2-007-C1", description: "Encryption at rest (AES-256)", status: "not-implemented" },
        { id: "SOC2-007-C2", description: "Encryption in transit (TLS 1.2+)", status: "not-implemented" },
        { id: "SOC2-007-C3", description: "Data classification and segregation", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-008",
      name: "Confidentiality — Data Disposal Procedures",
      description: "Establish secure data disposal procedures for media, devices, and data that is no longer needed.",
      category: "confidentiality",
      framework: "SOC2",
      status: "not-implemented",
      severity: "medium",
      implementation_guidance: "Document data retention schedule. Securely wipe or destroy media (NIST 800-88). Cryptographic erasure for cloud storage. Certificate of destruction. Logging of disposal events. Periodic review of retention compliance.",
      checks: [
        { id: "SOC2-008-C1", description: "Data retention schedule documented", status: "not-implemented" },
        { id: "SOC2-008-C2", description: "Secure media disposal (NIST 800-88)", status: "not-implemented" },
        { id: "SOC2-008-C3", description: "Disposal events logged", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-009",
      name: "Privacy — Data Retention and Disposal",
      description: "Retain personal data only as long as needed for the stated purpose, then securely dispose of it.",
      category: "privacy",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Define retention periods per data category. Implement automated data expiration/deletion. Document legal basis for retention periods. Regular purge cycles. Verify deletion is complete and irreversible. Maintain disposal audit trail.",
      checks: [
        { id: "SOC2-009-C1", description: "Retention periods defined per data category", status: "not-implemented" },
        { id: "SOC2-009-C2", description: "Automated data expiration implemented", status: "not-implemented" },
        { id: "SOC2-009-C3", description: "Disposal audit trail maintained", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-010",
      name: "Privacy — Consent and Choice Management",
      description: "Obtain and manage consent for data collection, use, and sharing. Honor opt-out requests.",
      category: "privacy",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement consent capture mechanism (cookie banner, registration form). Store consent records with timestamp and scope. Allow users to view, modify, and revoke consent. Honor deletion requests (GDPR Art 17). Process opt-outs within 30 days. Audit consent changes.",
      checks: [
        { id: "SOC2-010-C1", description: "Consent capture mechanism implemented", status: "not-implemented" },
        { id: "SOC2-010-C2", description: "Consent records stored with timestamp/scope", status: "not-implemented" },
        { id: "SOC2-010-C3", description: "Opt-out and deletion request handling", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-011",
      name: "Security — Vulnerability Management Program",
      description: "Implement a vulnerability management program including scanning, remediation SLAs, and penetration testing.",
      category: "vulnerability-management",
      framework: "SOC2",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Run automated vulnerability scans (SAST, DAST, dependency) in CI/CD. Monthly internal scans. Annual penetration testing. Remediation SLAs: Critical 7 days, High 30 days, Medium 90 days. Track findings to closure. Document risk acceptance for deferred items.",
      checks: [
        { id: "SOC2-011-C1", description: "Automated scanning in CI/CD", status: "not-implemented" },
        { id: "SOC2-011-C2", description: "Remediation SLAs defined and tracked", status: "not-implemented" },
        { id: "SOC2-011-C3", description: "Annual penetration testing", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-012",
      name: "Security — Incident Response Procedures",
      description: "Establish documented incident response procedures with defined roles, escalation, and notification requirements.",
      category: "incident-response",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Document IR plan with roles and contact lists. Define severity classification and escalation matrix. Conduct annual tabletop exercises. 24/7 incident monitoring (SIEM, on-call). Notification procedures (72h breach notification). Post-incident review and lessons learned.",
      checks: [
        { id: "SOC2-012-C1", description: "Documented IR plan with roles", status: "not-implemented" },
        { id: "SOC2-012-C2", description: "Annual tabletop exercises", status: "not-implemented" },
        { id: "SOC2-012-C3", description: "24/7 monitoring and on-call", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-013",
      name: "Security — Change Management",
      description: "Implement formal change management procedures for all system, software, and configuration changes.",
      category: "change-management",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "All changes require ticket, impact analysis, and approval. Peer code review required. Testing in non-production environment. Deployment windows. Rollback plan documented. Segregation of duties (developer ≠ deployer). Post-deployment verification.",
      checks: [
        { id: "SOC2-013-C1", description: "Change request and approval workflow", status: "not-implemented" },
        { id: "SOC2-013-C2", description: "Peer review and testing required", status: "not-implemented" },
        { id: "SOC2-013-C3", description: "Rollback plan documented", status: "not-implemented" },
      ],
    },
    {
      id: "SOC2-014",
      name: "Security — Risk Assessment Process",
      description: "Conduct periodic risk assessments to identify, analyze, and mitigate risks to the system and data.",
      category: "risk-management",
      framework: "SOC2",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Annual enterprise risk assessment. Risk register with owner, severity, mitigation. Vendor/third-party risk assessment. Track risk to closure. Risk acceptance requires documented sign-off. Integrate risk into change management process.",
      checks: [
        { id: "SOC2-014-C1", description: "Annual risk assessment performed", status: "not-implemented" },
        { id: "SOC2-014-C2", description: "Risk register maintained with mitigations", status: "not-implemented" },
        { id: "SOC2-014-C3", description: "Vendor/third-party risk assessments", status: "not-implemented" },
      ],
    },
  ];

  return {
    id: "soc2",
    name: "SOC 2 Type II Policy Pack",
    description: "AICPA SOC 2 Trust Services Criteria controls covering Security, Availability, Processing Integrity, Confidentiality, and Privacy.",
    version: "1.0.0",
    project_types: ["saas", "api-backend", "ai-application", "generic-web-application", "healthcare-system"],
    controls,
    frameworks: ["SOC2"],
  };
}
