# These are supported funding model platforms
# Displays a "Sponsor this project" button on the GitHub repo page
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: greenarmor
