# These are supported funding model platforms
# GitHub displays "Sponsor this project" button on the repo page
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: greenarmor
custom: ["https://ko-fi.com/greenarmor"]
