packages:
  - "packages/*"
linkWorkspacePackages: true
overrides:
  js-yaml: 4.3.0
  brace-expansion: 5.0.8
  postcss: 8.5.18
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@greenarmor/ges-audit-engine@1.1.2'
  - '@greenarmor/ges-cicd-generator@1.1.2'
  - '@greenarmor/ges-compliance-engine@1.1.2'
  - '@greenarmor/ges-core@1.1.2'
  - '@greenarmor/ges-doc-generator@1.1.2'
  - '@greenarmor/ges-git-hooks@1.1.2'
  - '@greenarmor/ges-mcp-server@1.1.2'
  - '@greenarmor/ges-policy-engine@1.1.2'
  - '@greenarmor/ges-report-generator@1.1.2'
  - '@greenarmor/ges-rules-engine@1.1.2'
  - '@greenarmor/ges-scanner-integration@1.1.2'
  - '@greenarmor/ges-scoring-engine@1.1.2'
  - '@greenarmor/ges-web-dashboard@1.1.2'
  - '@greenarmor/ges-audit-engine@1.1.5'
  - '@greenarmor/ges-cicd-generator@1.1.5'
  - '@greenarmor/ges-compliance-engine@1.1.5'
  - '@greenarmor/ges-core@1.1.5'
  - '@greenarmor/ges-doc-generator@1.1.5'
  - '@greenarmor/ges-git-hooks@1.1.5'
  - '@greenarmor/ges-mcp-server@1.1.5'
  - '@greenarmor/ges-policy-engine@1.1.5'
  - '@greenarmor/ges-report-generator@1.1.5'
  - '@greenarmor/ges-rules-engine@1.1.5'
  - '@greenarmor/ges-scanner-integration@1.1.5'
  - '@greenarmor/ges-scoring-engine@1.1.5'
  - '@greenarmor/ges-web-dashboard@1.1.5'
