import type { Control } from "@greenarmor/ges-core";

export function createArticle32Controls(): Control[] {
  return [
    {
      id: "GDPR-ART32-001",
      name: "Pseudonymisation",
      description: "Implement pseudonymisation as a technical measure to protect personal data.",
      category: "data-protection",
      framework: "GDPR",
      article: "Article 32(1)(a)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Replace identifying fields with pseudonymous identifiers. Maintain a separate, secured mapping table. Use tokenisation where applicable.",
      checks: [
        { id: "GDPR-ART32-001-C1", description: "Pseudonymisation strategy defined", status: "not-implemented" },
        { id: "GDPR-ART32-001-C2", description: "Technical implementation of pseudonymisation in place", status: "not-implemented" },
        { id: "GDPR-ART32-001-C3", description: "Mapping table secured with access controls", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-002",
      name: "Encryption at Rest",
      description: "Implement encryption of personal data at rest using approved algorithms.",
      category: "encryption",
      framework: "GDPR",
      article: "Article 32(1)(a)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Use AES-256-GCM or ChaCha20-Poly1305 for data at rest. Encrypt databases, file storage, and backups. Manage keys via vault or KMS.",
      checks: [
        { id: "GDPR-ART32-002-C1", description: "Database encryption enabled", status: "not-implemented" },
        { id: "GDPR-ART32-002-C2", description: "File storage encryption enabled", status: "not-implemented" },
        { id: "GDPR-ART32-002-C3", description: "Backup encryption enabled", status: "not-implemented" },
        { id: "GDPR-ART32-002-C4", description: "Key management via approved system (Vault/KMS)", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-003",
      name: "Encryption in Transit",
      description: "Ensure all personal data transmitted is encrypted using TLS 1.2 minimum.",
      category: "encryption",
      framework: "GDPR",
      article: "Article 32(1)(a)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Enforce TLS 1.2 minimum, prefer TLS 1.3. Configure HSTS. Disable older protocols. Use strong cipher suites.",
      checks: [
        { id: "GDPR-ART32-003-C1", description: "TLS 1.2 minimum enforced on all endpoints", status: "not-implemented" },
        { id: "GDPR-ART32-003-C2", description: "HSTS headers configured", status: "not-implemented" },
        { id: "GDPR-ART32-003-C3", description: "Strong cipher suites only", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-004",
      name: "Unique User Identification",
      description: "Ensure unique identification of each user through secure authentication.",
      category: "authentication",
      framework: "GDPR",
      article: "Article 32(1)(b)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement unique user IDs. Use Argon2id for password hashing. Support MFA and passkeys.",
      checks: [
        { id: "GDPR-ART32-004-C1", description: "Unique user identification implemented", status: "not-implemented" },
        { id: "GDPR-ART32-004-C2", description: "Secure password hashing (Argon2id)", status: "not-implemented" },
        { id: "GDPR-ART32-004-C3", description: "MFA support implemented", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-005",
      name: "Automatic Session Timeout",
      description: "Implement automatic session expiration after period of inactivity.",
      category: "authentication",
      framework: "GDPR",
      article: "Article 32(1)(b)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Set maximum session duration. Implement idle timeout (15-30 minutes). Require re-authentication for sensitive operations.",
      checks: [
        { id: "GDPR-ART32-005-C1", description: "Session timeout configured", status: "not-implemented" },
        { id: "GDPR-ART32-005-C2", description: "Idle timeout implemented", status: "not-implemented" },
        { id: "GDPR-ART32-005-C3", description: "Re-authentication for sensitive operations", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-006",
      name: "Audit Logging",
      description: "Maintain comprehensive audit logs of all access and processing activities.",
      category: "audit",
      framework: "GDPR",
      article: "Article 32(1)(b)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Log all authentication, authorization, data access, exports, and admin actions. Never log passwords, tokens, or sensitive data. Ensure logs are immutable.",
      checks: [
        { id: "GDPR-ART32-006-C1", description: "Audit logging system implemented", status: "not-implemented" },
        { id: "GDPR-ART32-006-C2", description: "Logs include required fields (userId, action, resource, timestamp, IP)", status: "not-implemented" },
        { id: "GDPR-ART32-006-C3", description: "Logs are immutable (append-only)", status: "not-implemented" },
        { id: "GDPR-ART32-006-C4", description: "Sensitive data is not logged", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-007",
      name: "Integrity Controls",
      description: "Implement measures to ensure ongoing integrity of personal data.",
      category: "data-integrity",
      framework: "GDPR",
      article: "Article 32(1)(b)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Use checksums or hashes for data integrity verification. Implement input validation. Use database constraints.",
      checks: [
        { id: "GDPR-ART32-007-C1", description: "Data integrity verification implemented", status: "not-implemented" },
        { id: "GDPR-ART32-007-C2", description: "Input validation on all data entry points", status: "not-implemented" },
        { id: "GDPR-ART32-007-C3", description: "Database constraints enforced", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-008",
      name: "Backup and Recovery",
      description: "Implement regular backup and recovery procedures for personal data.",
      category: "backup",
      framework: "GDPR",
      article: "Article 32(1)(b)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Perform daily encrypted backups. Test restores weekly. Conduct monthly recovery tests. Document backup procedures.",
      checks: [
        { id: "GDPR-ART32-008-C1", description: "Daily backup schedule configured", status: "not-implemented" },
        { id: "GDPR-ART32-008-C2", description: "Backups are encrypted", status: "not-implemented" },
        { id: "GDPR-ART32-008-C3", description: "Weekly restore tests performed", status: "not-implemented" },
        { id: "GDPR-ART32-008-C4", description: "Monthly recovery tests documented", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART32-009",
      name: "Regular Security Testing",
      description: "Conduct regular testing, assessment, and evaluation of security measures.",
      category: "security-testing",
      framework: "GDPR",
      article: "Article 32(1)(d)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Run dependency scans (Trivy, Dependabot). Perform secret scanning (Gitleaks). Use SAST (Semgrep). Schedule penetration tests.",
      checks: [
        { id: "GDPR-ART32-009-C1", description: "Dependency scanning in CI/CD", status: "not-implemented" },
        { id: "GDPR-ART32-009-C2", description: "Secret scanning in CI/CD", status: "not-implemented" },
        { id: "GDPR-ART32-009-C3", description: "SAST analysis integrated", status: "not-implemented" },
        { id: "GDPR-ART32-009-C4", description: "Penetration test schedule defined", status: "not-implemented" },
      ],
    },
  ];
}
