import type { Control } from "@greenarmor/ges-core";

export function createArticle5Controls(): Control[] {
  return [
    {
      id: "GDPR-ART5-001",
      name: "Lawfulness, Fairness, and Transparency",
      description: "Personal data must be processed lawfully, fairly, and in a transparent manner.",
      category: "data-processing",
      framework: "GDPR",
      article: "Article 5(1)(a)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement a consent management system. Maintain a record of legal bases for each processing activity. Provide clear privacy notices.",
      checks: [
        { id: "GDPR-ART5-001-C1", description: "Legal basis documented for each processing activity", status: "not-implemented" },
        { id: "GDPR-ART5-001-C2", description: "Privacy notice is clear and accessible", status: "not-implemented" },
        { id: "GDPR-ART5-001-C3", description: "Consent mechanism implemented where required", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART5-002",
      name: "Purpose Limitation",
      description: "Personal data must be collected for specified, explicit, and legitimate purposes.",
      category: "data-processing",
      framework: "GDPR",
      article: "Article 5(1)(b)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Document all purposes of data processing. Implement controls to prevent processing beyond declared purposes.",
      checks: [
        { id: "GDPR-ART5-002-C1", description: "Purpose of each data collection documented", status: "not-implemented" },
        { id: "GDPR-ART5-002-C2", description: "Technical controls prevent unauthorized purpose deviation", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART5-003",
      name: "Data Minimisation",
      description: "Personal data must be adequate, relevant, and limited to what is necessary.",
      category: "data-processing",
      framework: "GDPR",
      article: "Article 5(1)(c)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Review data collection forms and APIs to ensure only necessary data is collected. Remove unused data fields.",
      checks: [
        { id: "GDPR-ART5-003-C1", description: "Data collection reviewed for minimisation", status: "not-implemented" },
        { id: "GDPR-ART5-003-C2", description: "No unnecessary data fields in forms and APIs", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART5-004",
      name: "Accuracy",
      description: "Personal data must be accurate and, where necessary, kept up to date.",
      category: "data-quality",
      framework: "GDPR",
      article: "Article 5(1)(d)",
      status: "not-implemented",
      severity: "high",
      implementation_guidance: "Implement data validation on input. Provide user self-service for data updates. Schedule periodic data accuracy reviews.",
      checks: [
        { id: "GDPR-ART5-004-C1", description: "Input validation implemented for personal data", status: "not-implemented" },
        { id: "GDPR-ART5-004-C2", description: "Users can update their own data", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART5-005",
      name: "Storage Limitation",
      description: "Personal data must be kept in identifiable form no longer than necessary.",
      category: "data-retention",
      framework: "GDPR",
      article: "Article 5(1)(e)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Define retention periods per data category. Implement automated deletion or anonymisation. Document retention policies.",
      checks: [
        { id: "GDPR-ART5-005-C1", description: "Retention periods defined per data category", status: "not-implemented" },
        { id: "GDPR-ART5-005-C2", description: "Automated deletion or anonymisation implemented", status: "not-implemented" },
        { id: "GDPR-ART5-005-C3", description: "Retention policy documented", status: "not-implemented" },
      ],
    },
    {
      id: "GDPR-ART5-006",
      name: "Integrity and Confidentiality",
      description: "Personal data must be processed with appropriate security measures.",
      category: "security",
      framework: "GDPR",
      article: "Article 5(1)(f)",
      status: "not-implemented",
      severity: "critical",
      implementation_guidance: "Implement encryption at rest and in transit. Use access controls. Ensure data integrity checks.",
      checks: [
        { id: "GDPR-ART5-006-C1", description: "Encryption at rest configured", status: "not-implemented" },
        { id: "GDPR-ART5-006-C2", description: "Encryption in transit enforced (TLS 1.2+)", status: "not-implemented" },
        { id: "GDPR-ART5-006-C3", description: "Access controls implemented", status: "not-implemented" },
      ],
    },
  ];
}
